### ISSUE TITLE
Playlists take a long time to update

### ISSUE THREAD

**Issue by PeteRepeat77** [simon-weber/Autoplaylists-for-Google-Music#10]
I hope this the right way to post problems.. First day on github and not familiar with how it all works.

I created a playlist with rating "does not equal" certain values (0 to 5 I believe play uses). On the extension it says there are songs that fit the category of the playlist but google play music see only empty playlists. Although the playlists names  are in my library, just empty.

**Comment by simon-weber** [comment]
> I hope this the right way to post problems.

Yup!

Can you open the background script log (click the "background page" link by the "Inspect views" section on chrome://extensions), then hit the "force update of track cache..." button? The log output will help us narrow down what's going on.

**Comment by PeteRepeat77** [comment]
Will do that when I get back to the office in 14 hours. I did try the force
update after it didn't work.

I will also repeat the same playlist at home to see if its any different.

**Comment by PeteRepeat77** [comment]
The 5 star rating was well over 1000 tracks, like 3.6k. The other 1 star was 400 odd according to the when I click test. But both playlists are empty, bu do actually appear in play music

[Rating equals 1.txt](https://github.com/simon-weber/Autoplaylists-for-Google-Music/files/43607/Rating.equals.1.txt)
[Rating equals 5.txt](https://github.com/simon-weber/Autoplaylists-for-Google-Music/files/43608/Rating.equals.5.txt)

**Comment by simon-weber** [comment]
Hm, everything looks pretty normal to me in the logs. And since the remote playlist actually got created, there probably wasn't a problem with auth.

The equals 1 playlist is particularly weird, since it saw a response from Google indicating that those tracks were in the playlist. Sometimes the changes can take a few seconds to show up -- if you look at the playlists today, are they still empty?

**Comment by PeteRepeat77** [comment]
The one star one is now populated. But took quite a while. I checked after
quite a while, and tried many browser closes, reloads and logging out. Buts
it's there this morning so all good.

But the 5 star one is still empty.

**Comment by simon-weber** [comment]
Ok, good to know about the 1 star list. There's a clientside-initiated cache invalidation protocol that I haven't implemented, but retrying the idempotent updates has worked well enough in my testing.

The 5 star playlist probably has to do with 1k+ support (https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/5). I'll play around with it when I have a chance.

**Comment by PeteRepeat77** [comment]
Great.

On another note, any idea what the "unrated" rating is? I thought it was
blank or "null" but I added a new album and I think it came up in anything
I tried for a value.

What I want to get to eventually is create a Thumbs up (4 or 5 star) and
Unrated playlist.

So far your extension seems to have some great promise for this.

I'm happy to donate if you are planning that at any time, as what you are
doing is something I thought google would have implemented... But they
haven't and doesn't seem like they have any plans to either.

**Comment by simon-weber** [comment]
> On another note, any idea what the "unrated" rating is?

Without the 5-star ratings lab, it should be 0, 1, or 5 for no thumb, down thumb, up thumb, respectively (I had to look this up from the [gmusicapi docs](http://unofficial-google-music-api.readthedocs.org/en/develop/reference/mobileclient.html#gmusicapi.clients.Mobileclient.change_song_metadata)).


> I'm happy to donate if you are planning that at any time

Thanks! I'm still thinking about if/how to charge. My most recent idea is something like:
* free tier: all features, but limited to one playlist
* full tier: no limit on playlists. $1 a month?
* keep everything open source. contributors get full tier for free (by adding their email to be a trusted tester, which I need to check doesn't violate some ToS).
* people can build from source and sideload if they really don't feel like paying

But that's still at least a month or two away, so I'm not worrying about it for now.

**Comment by johnrobertlawson** [comment]
Unfortunately, I waited about 18 hours and still no songs in the playlists. I can take some logs if that's helpful? Tested on both Mac OS X 10.11 and latest version of Chrome OS.

**Comment by simon-weber** [comment]
Huh, sorry for the trouble, @johnrobertlawson. Let's take a look at the logs (instructions in https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/10#issuecomment-159497584). Feel free to paste them inline with triple backticks.

**Comment by johnrobertlawson** [comment]
I've attached the log file, seeing as Markdown was making a mess of my inline code.

[hjigmfiohhedacoipgnjbcmooocdljmo-1448648256525.txt](https://github.com/simon-weber/Autoplaylists-for-Google-Music/files/45994/hjigmfiohhedacoipgnjbcmooocdljmo-1448648256525.txt)

Hope this helps. As you can see, there are two playlists it's trying to sync, "Latest_loved" and "2015 Faves".

**Comment by simon-weber** [comment]
Hm, it looks like the editplaylist requests are nooping for some reason.

Let's take a closer look at the requests being sent. @johnrobertlawson, can you send me a HAR? Here are instructions in case you need them:
* open the background script dev tools as before
* click the "network" tab (instead of the "log" tab)
* click the small "clear" icon in the top left (just to the right of the record button)
* in another tab, hit the "force update of..." button. You should see three network requests show up in the network tab
* right click on any of them and select "Save as HAR with content"
* email the HAR to me instead of uploading here (since it'll contain session cookies -- even though they shouldn't be sufficient to let someone mess with your account, we should avoid posting them publicly)

That should be enough for me to figure out what's going on.

**Comment by johnrobertlawson** [comment]
OK, cheers; just sent that now.

**Comment by simon-weber** [comment]
Perfect, thanks @johnrobertlawson.

I think I figured it out: you use All Access, right? It seems like any tracks of type 7 (which I got by adding an All Access track to my library) don't add since Google wants the store id and not the library id. Looks like an easy fix :+1:

**Comment by johnrobertlawson** [comment]
Correct! GPAA has a nasty habit of removing items from your Library and re-adding them, or something it doesn't re-add them but preserved your thumbs-up rating. Glad it isn't terminal!

**Comment by simon-weber** [comment]
@johnrobertlawson alright, I think https://github.com/simon-weber/Autoplaylists-for-Google-Music/releases/tag/0.1.2 should fix this. Give it a shot and let me know if it works for you.

**Comment by johnrobertlawson** [comment]
It's working, though the Google Music webpage appears to be overloading on memory or something, and reloads the playlist non-stop, and become unresponsive. I noticed the order of the playlist and number of tracks is fluctuating too. This could just be a temporary thing as it chugs through the logic of sorting the playlist?

**Comment by simon-weber** [comment]
@johnrobertlawson I triggered that at one point -- I think it has to do with existing state when syncing. Can you try deleting all the tracks in the playlist and then re-syncing?

**Comment by johnrobertlawson** [comment]
Unfortunately Google Play Music locks up too much to do anything via web interface. However, I noticed via Gear Player for Mac that tracks were being duplicated 2-5 times in some cases, and the playlist length was getting much larger than the size when you "Test" in the extension script.

**Comment by simon-weber** [comment]
Hm, I just tried manually duplicating different types of tracks and wasn't able to recreate this.

You can manually kill the background script by opening the Chrome task manager. That should get the web interface responsive again.

**Comment by johnrobertlawson** [comment]
OK, I deleted all and waited for the resync, and now different tracks are duplicated in the playlist. Seems random (there are no duplicates in my actual library). After two minutes or so, the webpage refreshes and the playlist length shortens but all duplicates are gone, and everything seems OK! 

So after creating a playlist, there's a few minutes of flux where the webpage is not responsive and there a lots of duplicates, but afterwards the playlist is fixed. However, the page still refreshes every minute or so and locks up temporarily, presumably as the script is checking the remote playlist?

**Comment by simon-weber** [comment]
Got it. Let's move this to https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/17 now that we've seemingly fixed the problem with AA tracks not appearing.
