### ISSUE TITLE
Cannot update or reinstall extension after cancelling subscription 

### ISSUE THREAD

**Issue by jpaechnatz** [simon-weber/Autoplaylists-for-Google-Music#102]
...I tried the extension with subscription some time ago. 

I like to give it a try again and as it was not autoupdating in chrome. I removed it but cannot reinstall it.
Any ideas?

**Comment by simon-weber** [comment]
I'm pretty sure this is a bug on Google's end :disappointed: I've got a ticket open with Google about it already.

My understanding of how to reproduce it is:
* install and subscribe to paid version
* get charged at least once
* cancel subscription and uninstall
* reinstall: the install screen now either hangs or gives an error like "permission denied"

Does that match what you've experienced? I'm not aware of problems with updating, but it'd seem consistent that if the Web Store doesn't allow reinstalling, it'd also prevent updating. Let me know and I'll send it Google's way to try and prod them into fixing it.

In the meantime, the only workarounds I'm aware of are:
* sign into Chrome with a different account, since the bug is tied to the account you used to purchase the extension
* [run from source](https://github.com/simon-weber/Autoplaylists-for-Google-Music#development-workflow): if the instructions are too much, feel free to send me an email and I can send you a copy to install. Auto-updating won't work, though, and you'd need to install it manually on each machine.

**Comment by jpaechnatz** [comment]
Exactly my situation! And I like to try the source version.

**Comment by jpaechnatz** [comment]
Ok. Tried a git clone...  I can load the src folder as unpacked extension. The extension icon is shown, but no options etc. within loaded play music.  Do I need watch.sh ? Or are those .sh scripts for your  internal use only?

**Comment by simon-weber** [comment]
You should just have to run the build.sh script and then reload the src folder (which will now have compiled source in js-built).

**Comment by jpaechnatz** [comment]
Just.. well. ;-)
npm install -g browserify
npm install -g exorcist
npm install -g jquery
npm install -g jquery-modal

 ./build.sh 
....Error: Cannot find module 'jquery' from '/home/joh/source/Autoplaylists-for-Google-Music/node_modules/jquery-modal'
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
The code that you piped into exorcist contains no source map!
Therefore it was piped through as is and no external map file generated.
...Error: Cannot find module 'jquery' from '/home/joh/source/Autoplaylists-for-Google-Music/node_modules/jquery-modal'
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
The code that you piped into exorcist contains no source map!
Therefore it was piped through as is and no external map file generated.
............done

Althought this error is shown, the extension loads. Should it work? And could I give the subscription a try?

**Comment by jpaechnatz** [comment]
... some parts are missing, and I cannot add rules, the "Explanations of fields" is empty.

**Comment by simon-weber** [comment]
Huh, sorry about that. I'll build you an archive and work on making it recreateable when I have a chance.

**Comment by simon-weber** [comment]
Ok, unzip this and load it as an unpacked extension: [1c717968b30ea04230472df84aaf83c8ae9335c9.zip](https://github.com/simon-weber/Autoplaylists-for-Google-Music/files/537597/1c717968b30ea04230472df84aaf83c8ae9335c9.zip).

**Comment by jpaechnatz** [comment]
Works. Only reenabling subscription seems being impossible. Thanks so far.

**Comment by simon-weber** [comment]
Ah, yeah, that build isn't tied to the web store's licensing system at all. Instead, you should see a button like "enable full license" -- that's what I use for testing code specific to each version. After hitting that, the full version should be enabled on that machine. Feel free to use it while we're waiting on Google to fix their end.

**Comment by jpaechnatz** [comment]
Thanks again.

**Comment by simon-weber** [comment]
@jpaechnatz Google tells me they've fixed this now! Can you give the web store another shot?

**Comment by jpaechnatz** [comment]
does still not work. No way to install via "app store".

**Comment by simon-weber** [comment]
Bummer. I'll get back in touch with Google.

If you don't mind being put in touch with their support people directly, shoot me an email. My repro instructions were pretty precise but didn't work, so I suspect they'll want to reach out to users directly to be able to replicate this.

**Comment by simon-weber** [comment]
After months of teeth pulling, they've finally acknowledged the problem has always existed. No ETA on a fix, but at least it's progress.

**Comment by simon-weber** [comment]
If anyone's still able to reproduce this, can you give this a shot:
* open the extension's interface (where it lists your playlists)
* [open the dev tools](https://developer.chrome.com/devtools#access)
* click the console tab
* enter `$('#check-license').click()` and hit enter. you should see a line that says "got license response..."
* expand the object on that line and paste it back here (there's nothing sensitive in it)

It should look something like this:
```
accessLevel:"FREE_TRIAL"
createdTime:"1451689404556"
itemId:"blbompphddfibggfmmfcgjjoadebinem"
kind:"chromewebstore#userLicense"
maxAgeSecs:"2"
result:true
```

**Comment by simon-weber** [comment]
Alright, I'm told this is fixed, hopefully for real this time. I'll reach out to users over email; hopefully someone can still test it.
