### ISSUE TITLE
Playback on iPhone7 does not update the "Play Count" or "Last Played" timestamp

### ISSUE THREAD

**Issue by yokaiichi** [simon-weber/Autoplaylists-for-Google-Music#103]
This might be totally out of your control, and instead a bug with Google Play Music on iOS 10. I've verified and tested on my own setups. If I play a song in a web browser on any Windows 10 machine, the "Last Played" and "Play Count" values are getting updated correctly. But if I play that same playlist from my iPhone7, it doesn't update either value.

It's worth noting that my primary workflow is to download the Autoplaylists so they are resident in iPhone memory, so playing them is not using streaming to/from Google. Still I expected that playcounts/lastplayed timestamps etc. would be internally tracked and updated to Google when connectivity permitted.

**Comment by simon-weber** [comment]
Huh. Yeah, that sounds like an issue on Google's end; I've relied on this from android in the past. If you check back much later (say, 24 hours), do the values change?

**Comment by yokaiichi** [comment]
Further testing:

- Neither Play Count nor Last Played update when the autoplaylist has been "pinned" (downloaded) to the iPhone memory for offline play and the playlist is played from the phone.
- Play Count is updated when played from a Web browser even if you start a song and then quickly skip forward to the next song in the playlist. However, Last Played is _not_ updated.
- Last Played is updated only when played from a browser AND you let normal playback trigger the end of the song. In other words, let it play through normally, or else start the song, manually drag the scrubber near the very end, and then let playback resume to naturally run through the end of the song.

Kind of a hassle when you primarily use "last played" conditions in your playlists and you rely on phone playback to get EQ the way you want it in your headphones (and commute a lot). Not sure you can do anything about this on your end though.

**Comment by simon-weber** [comment]
Yeah =/ I'll tag it as a google bug for now; hopefully it gets fixed.

Kind of related: I know there is (or at least used to be) weird behavior around when play count is incremented across different types of songs. See https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/18#issuecomment-164203689 for more details.

**Comment by simon-weber** [comment]
And for what it's worth, this doesn't even seem to be the worst bug in that release, haha: https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/101.

**Comment by simon-weber** [comment]
I haven't heard of this being a problem in a while, so I think Google may have fixed it. Feel free to comment if it's still an issue and I'll reopen.
