### ISSUE TITLE
subscription (All Access) tracks aren't included by linked playlists rules ("playlist equals...")

### ISSUE THREAD

**Issue by BroskiSabor** [simon-weber/Autoplaylists-for-Google-Music#107]
Forgive if this issue has been brought up before, I looked through the closed issues and did not see someone with a similar issue. When trying to combine two separate playlists into one (to bypass 1k song limit), the only tracks populated are those that I have uploaded, which make up a small number of songs compared in my library compared to those on the All Access servers. These are the conditions I'm setting:

Any of the following:
        Playlist equals... playlist 1
        Playlist equals... playlist 2

Am I doing something wrong or is this a known bug?

**Comment by simon-weber** [comment]
Huh, I haven't heard of this being a problem, and it should be supported. Are playlist 1 and 2 in this example other autoplaylists, or normal static playlists? I'll try to recreate it when I get a chance.

In the meantime, can you try adjusting the sort order of the combined playlist in the off chance all the AA tracks are just sorted after the limit?

**Comment by BroskiSabor** [comment]
Wow, thank you for the quick response. These are both just static playlists, not auto playlists. I tried changing the way they were sorted (had it set to random the first go-round) and no changes.

**Comment by simon-weber** [comment]
Sounds good! I'll see what I can find out.

**Comment by simon-weber** [comment]
Alright, I found the problem. It looks like Google has switched a response format: instead of returning the library id in first position for playlist entries, they're now returning the store id for AA tracks. Since the playlist linking code expects a library id, it never finds the AA tracks when it's building out the combined autoplaylist.

I don't see any easy workarounds, unfortunately. I'll work on a fix.

**Comment by simon-weber** [comment]
Thankfully this was an easy fix! Thanks for reporting it.

I'll cut version 2.0.5 now. To get the fix asap head to chrome://extensions and hit "Update extensions now". It might take a few minutes until Google has it ready to send out.

**Comment by BroskiSabor** [comment]
Just updated and everything is working perfectly now, thank you for the lightning-quick fix!
