### ISSUE TITLE
Seems to disable when I quit Chrome and can't re-enable.

### ISSUE THREAD

**Issue by PeteRepeat77** [simon-weber/Autoplaylists-for-Google-Music#11]
Sorry but I don't have a debug but happy to do so if you suggest the best method (seeing it doesn't happen during usage).

I think the extension gets de-activated, perhaps due to security settings.
<img width="593" alt="autoplaylist screenshot" src="https://cloud.githubusercontent.com/assets/15964601/11412615/23862d0c-9433-11e5-9de3-aa81d2929975.PNG">

**Comment by PeteRepeat77** [comment]
I understand this probably won't be a problem when it goes on the chrome store however.

**Comment by PeteRepeat77** [comment]
I seemed to have fixed it for now. I unpacked the crx file using 7zip. Then dragged the folder into the extension tab and chose to install. Doesn't seem to have the "not from chrome store" installed this way, like dragging and dropping the crx file had.

**Comment by simon-weber** [comment]
I wonder if that was a leftover source install? I thought I changed the version of the crx to be 0.0.1, not 0.1.

**Comment by simon-weber** [comment]
Welp, apparently I just messed up the version number: it's definitely 0.1 on the release crx, not 0.0.1. I'll package a new release asap.

I haven't been able to recreate the disabling behavior. I do get the "not from the chrome web store" label, but it stays enabled between restarts.

**Comment by PeteRepeat77** [comment]
It appears that it is quite common with extensions not on the chrome store
being disabled. One work around was what I did, but it appears like the
extension has now uninstalled itself (not just disabled) again so the fix
was short lived... Chrome removes the extension folder as well. I'll keep
looking into it.

**Comment by PeteRepeat77** [comment]
I don't seem to have the problem at all now, so happy you mark this as solved if it helps remove congestion. If I find it deactivating I'll investigate it further before raising another issue.

**Comment by simon-weber** [comment]
Huh, ok. Feel free to reopen if it becomes a problem again.

**Comment by PeteRepeat77** [comment]
Unfortunately chrome has disabled the extension again when I came back to use it. It was installed using drag and drop of the crx file. 

Says the developer needs to upload it to the chrome store for them not to disable it.

The extension can't enabled again, and requires to be reinstalled which isn't ideal. 

Any plan to upload to the store or is that some time away?

**Comment by simon-weber** [comment]
Huh. Is that the exact wording of the error message? I can't seem to find any docs about this behavior.

> Any plan to upload to the store or is that some time away?

I think I'll be able to get to that in the next day or two =) I just need to finish up a drag-and-drop import/export to ease the transition across multiple copies of the extension.

**Comment by simon-weber** [comment]
@PeteRepeat77 ok, I've published a Web Store version: https://chrome.google.com/webstore/detail/autoplaylists-for-google/blbompphddfibggfmmfcgjjoadebinem. It's not publicly visible; you'll need to be logged into an account that's a member of [the mailing list](https://groups.google.com/forum/#!forum/autoplaylists-for-google-music) to install it.

I'll wait to announce it on the mailing list until I hear back from you.

**Comment by PeteRepeat77** [comment]
So far it looks like the store install is all good. No "not installed from the store" (or similiar) anymore so can't see it getting disabled. 

Good to close this issue again as far as I'm concerned.

**Comment by simon-weber** [comment]
Great!
