### ISSUE TITLE
random sort docs unclear as to when reseeding happens

### ISSUE THREAD

**Issue by Leviathan1753** [simon-weber/Autoplaylists-for-Google-Music#112]
I seem to be getting the same random results despite re-syncing my autoplaylist.

My rules currently are:
 - a genre exclusion of "Ambient"
 - rating thumb doesn't equal "down"
 - sort by random ascending

I have the sync period set to 2 minutes, just to test.  Overall, nothing too fancy.. just a new set of songs every sync that aren't thumbs down.

However, the random sort seems to have given me an initial random set, but the results seem to be the same every sync;  I get the same random 1000 songs every time out of my 14k song library.   Does the random not change seed every run?  Is there some other reason I'm not getting a new set of songs every 2m?

**Comment by simon-weber** [comment]
Ah, this might just be a problem with the docs: the sort order will change each time the _tab_ is reloaded, not for each sync. Try refreshing the tab and see if the order changes.

**Comment by Leviathan1753** [comment]
That does seem to work.  I refreshed my tab, let it resync, and a new set of songs showed up.

Can we get an option to have it do a new random every sync?  It would be useful for how I intend to use the system.  Or is there some technical limitation that prevents that?

Thanks for the plugin!

**Comment by simon-weber** [comment]
It's not impossible, but I wouldn't recommend it. I think you'd see:
* songs cut off often: Google's client will stop playing a song if it's removed from a playlist, which would happen if it gets ordered out of the 1k that are included. The extension could try and work around this, but it wouldn't be straightforward.
* much slower sync times: Google's servers use what seems to be an append-only store, so reorders are a more expensive operation than you'd expect. Putting too much strain on them causes issues like https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/104.

What's your ideal playlist setup look like? Maybe there's a way we can get that with the current setup. For example, I use a pomodoro playlist like https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Tips-and-Tricks#pomodoro-playlist.

**Comment by Leviathan1753** [comment]
My typical usage is a "furnace" playlist.   Anything I remotely think I'll like or got recommended to me I throw on a large shuffled list.  Eventually it'll come up and I'll over time decide if I like something or not by starring/liking/removing.   The one caviat that throws a wrench into the idea is I have a truckload of "ambient" songs in my library, which I don't want on this furnace list.  This makes just putting all songs in my library on shuffle a not viable option.  This is where autoplaylist would hopefully solve the problem.

My setup would hopefully just use this autoplaylist as a substitute.  I'd add things to my library and then use this auto playlist to make a random 1000 song playlist that's hopefully always fresh with a random set of songs when I need it.  It's fine if it only refreshes once every few hours, or even less frequent if needed.   Needing to manually refresh a tab to make this re-randomize sort of messes it up.. but I suppose it would generally happen often enough not to matter too much.   But in an ideal world it would refresh periodically without needing babysitting.

If it is a heavy operation to re-randomize, I could put up with limiting the list to smaller numbers like 100, and having it re-sync only every 3 hours or something.

**Comment by simon-weber** [comment]
Got it. One thing that could be useful is having a way to tell the new and evaluated tracks apart (I could last played, playcount, date added to library and rating all being useful depending on your setup). If you have a way to do that, then you can make your autoplaylist only include unevaluated tracks. Then each sync would remove a few tracks that you've evaluated and replace them with any you haven't, which would avoid the need to manually refresh to get fresh tracks (and ought to be much easier on Google's servers to boot).

**Comment by Leviathan1753** [comment]
Yeah, I actually was using a "not played within 60 days" filter initially.  Then I had the suspicion that when that timed out and a song came back up it would jump to the front of the list due to having the same random seed.  The end result would I'd only be listening to the same tracks that I was able to "get through" in the 60 days, and unlucky tracks in the back would just never trickle up far enough.

However, I just realized that a 60 day block + im sure I'll refresh the tab within those 60 days should make that a moot point.

For the short term, I'll just re-add the 60 day block and proceed ahead. 8)
But an option to re-random on seed would still be a good option to have overall, I think.

Thanks for the help!

**Comment by simon-weber** [comment]
Sounds good! I'll adjust this issue to track improving the docs and make a new one for better control over reseeding.

**Comment by Leviathan1753** [comment]
Came back to report some bad news.

The random seed seems to not be reset anymore by reloading or reopening a google music tab.  I've reloaded/reopened several times and none of my playlists re-randomize.  8(

Don't know what changed.. maybe something on Google's end?

**Comment by simon-weber** [comment]
Hm, thanks for the heads up. I got an email the other day with someone reporting reseeding when they didn't expect it, so there might be something larger going on. I'll have plenty of time to look into it next week.

In the mean time, [reloading the extension](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#reloading-the-extension) and [checking your logs](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs) is always worth a shot.

**Comment by Leviathan1753** [comment]
Disabling/Re-enabling the plugin did the trick!  Thanks man

If it happens again, I'll see if I can grab a log dump for you

**Comment by simon-weber** [comment]
Ah, good to hear. I do think there's some kind of issue with the new syncing code that gets  triggered after running for a long time (and maybe getting deauthed). https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/114 should suss out a variety of edge cases like that.
