### ISSUE TITLE
Dynamic 'last played' date

### ISSUE THREAD

**Issue by johnrobertlawson** [simon-weber/Autoplaylists-for-Google-Music#12]
Is there a way to have 'not played in the last 30 days' or something like that? What's the syntax as it stands regarding last-played?

**Comment by simon-weber** [comment]
Yup, though it's not in the packaged release yet. You can do `last played, before, "30 days ago"` in the source release.

Anything from http://sugarjs.com/date_formats should work.

**Comment by johnrobertlawson** [comment]
Excellent, thanks.

**Comment by simon-weber** [comment]
Will track improving the docs in https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/13.
