### ISSUE TITLE
Regex Examples

### ISSUE THREAD

**Issue by Yinka** [simon-weber/Autoplaylists-for-Google-Music#123]
A question rather than issue.

Regex examples will be great, I tried a couple with pipes but doesn't seem to work for me, n00b here

Also what does `Last Played (Entire Album)` do?

Is the `id` the Google's `song id` or your assigned `id` ?

Thanks

**Comment by simon-weber** [comment]
Sure. Here's a few regex examples:
* `(metal)|(rock)` would match "rock", "alternative rock", and "progressive metal", but not "jazz" or "Rock" (it's case sensitive). Note that you could also accomplish something similar with the subrule `ANY (genre contains metal), (genre contains rock)`.
* `^..*(Of)|(The)|(A)` could help find improperly-capitalized tracks, matching "Walls Of Jericho" but not "The Skull". See [these docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Special_characters_meaning_in_regular_expressions) for an explanation of the special characters.

Sites like http://www.regextester.com can help when working on them. Note that I don't currently support a way of setting flags: you're just filling in the part between the forward slashes.

>  what does Last Played (Entire Album) do?

For a track T in album A, it's the last time you listened to album A in one sitting. To be honest, though, I have no idea if it works as expected, haha. Let me know if you have a counterexample to that.

> Is the id the Google's song id or your assigned id ?

"id" is what I call the "library id": it's assigned by Google on a per-account basis. If you upload multiple copies of the same song, each will have a different library id (and if your friend uploads the same song, they'll also get a different library id).

The "store id", on the other hand, is unique across all accounts. If you and a friend both add the same All Access track to your library, it will have the same store id but different library ids.

Hope that helps! I'll use this ticket to track putting improved explanations in the ui (or maybe the wiki).

**Comment by simon-weber** [comment]
Ah I'm already tracking that in https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/93. I'm going to close this, but feel free to add another comment if you have more questions.
