### ISSUE TITLE
Playlist exclusion order returns different results

### ISSUE THREAD

**Issue by metalgeekstl** [simon-weber/Autoplaylists-for-Google-Music#126]
It seems the order which I exclude playlists either causes 0 results, or expected results. Example below:

1. up-least:
ALL of the following conditions
rating thumb = up
sort by - play count ascending

RESULT: 150 tracks

2. up-old:
ALL of the following conditions
rating thumb = up
playlist =/= up-least
sort by - last played ascending

RESULT: 30 tracks

Now I put these two as exclusions

3. up-random
ALL of the following conditions
rating thumb = up
playlist =/= up-least
playlist =/= up-old

RESULT: 0 tracks

But if I switch the order to:

playlist =/= up-old
playlist =/= up-least

RESULT: 35 tracks (as I'd expect it to be)

So it looks like the order which I place these playlist exclusion matters, but I'm not sure how. Perhaps playlists containing exclusions themselves must go first, otherwise 0 results are returned.

**Comment by simon-weber** [comment]
Interesting; thanks for reporting it. My bet is that there's a bug in the cycle detection.

Glad you have a workaround meanwhile.

**Comment by metalgeekstl** [comment]
It seems that any playlist that includes a playlist exclusion cannot itself be added to any playlists. Either it doesn't add it's tracks, or it breaks everything and nothing is returned. If I add 1. up-least AND 2. up-old, it only shows the results of 1 because it doesn't contain any playlist exclusions. Strange since it should only work the results of the playlist+exclusion, not the rules inside it.

**Comment by simon-weber** [comment]
I'm having trouble replicating this. Can you double check that those playlist definitions match what you're using? In particular, I'm wondering if there are limits involved, since otherwise I think up-old should be empty (it includes only up-thumb tracks, then excludes them through the other playlist).

**Comment by simon-weber** [comment]
Ah, nevermind, I managed to reproduce it with some slightly different playlists. It does seem to be a problem with cycle detection.

**Comment by metalgeekstl** [comment]
OK. Yes up-least has a 134 limit. I wasn't able to work around the odd
behavior of the order of excluded playlists. Seems no rhyme or reason to
how it behaves. Thanks for your hard work!

**Comment by simon-weber** [comment]
In retrospect this was a pretty obvious bug, haha. It just triggers in a relatively rare situation, so I guess nobody had stumbled across it until now.

I'll cut a release for this shortly.
