### ISSUE TITLE
Google Music ui continuously refreshing

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/Autoplaylists-for-Google-Music#127]
@dvvilkins reported these symptoms in https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/20#issuecomment-275967478. I moved it here to avoid reopening an old issue.

@dvvilkins, what version of the extension are you running? It's listed next to the name at chrome://extensions. 

If you're up to date (5.1.4 is the latest), try to recreate the problem, [save your logs to a file](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs), and then email them to me. That should point us in the right direction.

**Comment by dvvilkins** [comment]
Hi Simon,

Thanks for offering to help.

I'm running version 1.352.0. of Google Play Music for Chrome. According to
the play store, 1.353 is the latest and was released yesterday Feb 2 (see
attachment) though mine won't seem to update to it.

Shall I clear the log first or just recreate the problem and send the whole
thing?

-Drew

**Comment by simon-weber** [comment]
Oh, whoops, I'm interested in the version of the autoplaylists extension. Can you check that too?

It is interesting that you're using the GPM extension -- does the problem also happen at https://play.google.com/music/listen?

Good question about the logs. It's probably best if you:

1. [reload the extension](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#reloading-the-extension)
2. recreate the problem
3. [save the resulting logs](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs)

that'll both clear the logs out and rule out anything fixed by a reload.

**Comment by bawlololinDale** [comment]
Hey, I had the same issue, but it wasn't due to this extension. The Play Music extension was constantly trying to upload music. I disabled that extension while trying to solve a different issue, and it stopped trying to upload and refreshing all the time.

**Comment by simon-weber** [comment]
Woah; thanks so much for getting in touch. I never would have guessed that in a million years.

**Comment by simon-weber** [comment]
I'm going to close this since I haven't heard back in a while. Feel free to respond if this is still and issue and I'll reopen it.
