### ISSUE TITLE
correct sort when testing, incorrect sort after syncing

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/Autoplaylists-for-Google-Music#133]
Originally reported in https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/109#issuecomment-282746238 by @Dasonk:

> I'm having an issue where I use an All condition and have two conditions (playlist = something, last played earlier than 2/27/2017 let's say). I can not get the sorting in google music to stick. The sorting when I choose "test" looks good but once it syncs to google music the playlist is not sorted the way I want it at all. Could this be related to this bug and if so is there anything I can do to help track down the issue?

**Comment by simon-weber** [comment]
A few questions to try and narrow this down:
* what's your sync period (in settings) set to?
* if you [check the logs](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs), do you see any syncing/reordering errors or warnings? My guess is that you'll see a bunch of "mixed reorder" warnings.

And some ideas to try to fix it:
* if you let the extension sync for a bit (say, 5 sync periods) does the ordering change? ie, does it eventually fix itself?
* if not, does manually clearing out the tracks from Google's playlist first help? The easiest way to do this is to select the first track, shift-click the second, then hit "select all" from the dropdown in the top right that says "2 selected".

**Comment by Dasonk** [comment]
1) Sync period is/was set to 5
2) I didn't see any mixed reorder warnings. There were no warnings of any kind (verified by filtering)

3) I wasn't paying the most attention but letting it sync once or twice seemed to *help* in a sense that it became somewhat more ordered but it wasn't the order it should be
4) Manually clearing out the tracks and letting a sync period repopulate the list did ultimately end up with the list ordered the way it should be.

**Comment by simon-weber** [comment]
Gotcha. Google's servers are known to handle reordering a bit strangely sometimes, but it tends to converge quickly enough that nobody notices. Good to know that flushing the playlist worked more quickly.

I'm going to close this out, but I'll open it back up if this becomes a regular occurrence.
