### ISSUE TITLE
only a subset of tracks are syncing

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/Autoplaylists-for-Google-Music#135]
Reported on [the mailing list](https://groups.google.com/d/msg/autoplaylists-for-google-music/AEG7_LAHqaE/sggllP-ACwAJ):
> The playlist appears, but number of songs in the new google playlist do not match the test playlist from your extension

What we know so far:
* the query works fine locally
* we're sending the expected tracks to Google and receiving a 200

I'm not sure yet what's causing this yet. What I've ruled out so far:
* https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/119: the query works correctly locally; it's just post-sync state that's wrong
* subscription tracks don't sync: it's a free account with all user-uploaded tracks
* general syncing problems: logs don't indicate that

My next guess is that it's matched tracks causing the problem.

**Comment by simon-weber** [comment]
Ok, here's a way to test if matched tracks are the problem:

* add the condition "type equals -1" to the playlist, then test it. The same number of tracks should appear, but the type should show up.
* click on the type header to sort by it, then note the type of the track that syncs (you may need to search for it) and the type of tracks that don't sync. Are there any patterns?

My guess is that the syncing track will be type 2, but the non-syncing tracks will be type 6.

For what it's worth, though, my account seems to be syncing both types fine right now. Maybe there's some other odd kind of track I'm not thinking of?

**Comment by ankurbs** [comment]
Simon, within the extension, when I try "-1" nothing appears, however, when i enter "-2" or "-6" tracks do appear. That being said, know it seems that no playlist syncs over. I did try reloading the extension, but that did not seem to solve the issue. I know I did stop uploading my tracks yesterday in the middle of uploading my entire library, so i am going to go home and see if i restart the upload from the beginning, if this will issue will be resolved. I will let you know. Thanks again!

**Comment by simon-weber** [comment]
Oh, my bad, I inverted it. I meant "type doesn't equal -1". My idea was just to pick a type that doesn't exist so that the type column shows up (only fields involved in the query show up).

**Comment by simon-weber** [comment]
Oh, and here's another thing to try when you have a chance:

* [open the logs](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs)
* click the "network" tab.
* ensure filters are off and recording is enabled, then wait for a sync. A few rows should appear.
* right-click the row with "plentriesbatch" in it (not "playlistbatch"), then hit "copy > copy response". It should start with `{"mutate_response":[{"id":"...`

Paste that back here (or to somewhere like pastebin if it's very large). That'll show us if Google is sending any more information back about why it's not accepting these tracks.

**Comment by ankurbs** [comment]
Simon,

I have finished uploading my entire library and the same issue exists. As
for the syncing of the music, based off what I am seeing, i don't see any
patterns. It appears that both type 2 and 6 songs are syncing and not
syncing.

That being said, I did run another test and this is even weirder.

The original genre that I was trying this was "Hindi Movie." Since that was
not working, I decided to try "Children's Music." The test showed 34 songs
and the synced playlist also showed 34 songs. I then tried my classical
music. The test showed "35" and the synced playlist showed "28" so I am
very confused. It seems that the metadata is off. I am going to see if I
can mass change the meta data for the songs to see if that will correct
this. Maybe something was messed up during the upload.

Ankur

**Comment by simon-weber** [comment]
Ok, thanks for checking the type.

My guess is that the genre and upload pause are both red herrings. Google's servers only take two params when adding a track: the type and the id. The correct way to send the a request depends on these two things, since tracks have multiple ids and different ones are used based on the type. This is probably what the problem is, though I'm not sure yet what's unique about your situation to cause it.

Can you try the instructions at https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/135#issuecomment-282843297? If we get lucky it'll tell us exactly what the problem is. If that doesn't help, I think the next step would be to capture Google's traffic to itself and compare it to ours.

**Comment by simon-weber** [comment]
I'm going to close this since I haven't heard back in a while. Feel free to respond if this is still an issue and I'll reopen it.
