### ISSUE TITLE
Ratings not importing to GPM

### ISSUE THREAD

**Issue by Jimmyt3477** [simon-weber/Autoplaylists-for-Google-Music#136]
This is not an issue directly with your extension (which I love), but does make your extension ineffective for me.  The issue is that of my ~7,000 song library, over 1,000 upload with no rating.  I have checked a number of these songs individually and can confirm that each has its proper rating in iTunes, Windows Media Player and with the file itself (viewed via Windows Explorer).  I've tried deleting the entire GPM library and re-uploading multiple times but no joy.  Anything else I can try?

**Comment by simon-weber** [comment]
I've got some ideas, but no silver bullets, unfortunately:

* try another kind of upload: for example, if you've always done folder-based uploading, try uploading from iTunes instead. Folder uploading will look directly at the files, but iTunes uploading looks at the iTunes db, so if iTunes can interpret the ratings you should be good.
* figure out what's different about tracks that do/don't upload ratings: after that, the problem reduces to batch-editing the broken ones and reuploading them. You'll want a tool that lets you see exactly which low level fields are set (maybe http://www.mp3tag.de/en?) to compare.
* crappy autoplaylists batch editing: 1) pick another field (maybe comment or album artist) that you don't currently use 2) in an editor that reads ratings correctly, set that comment to match the rating (eg comment field set to "rating=4") 3) reupload 4) make an autoplaylist querying your surrogate field (eg "comment equals rating=4" for each value) 5) in Google Music, select all tracks in the playlist and edit their rating

**Comment by Jimmyt3477** [comment]
On the last piece of your last point, how do you go about editing the
rating in Google Music.  I was under the impression that functionality has
been removed and you can now only thumb up/down for ratings?  I'm not
opposed to manually re-rating the items (have already isolated them in a
rating=0 autoplaylist) but didn't think that was possible.

Thanks so much for the quick reply and your help in trying to identify the
problem.  Your extension is just what I needed if I can ever get Google
Music to cooperate.  By they way, my mail goal in this is to have a service
that uses autoplaylists based on ratings, last played, etc. that will
update via plays through Sonos.

**Comment by simon-weber** [comment]
That's right: there's only up/down since the 5-star ratings lab was removed. Google coerces your ratings onto the 2-point scale.

Is it possible that's where your unrated tracks are coming from? Maybe 3-star tracks are coerced to no thumb?

**Comment by Jimmyt3477** [comment]
No - strangely enough the tracks showing zero have actual ratings that vary
from 2-5.  They also have a variety of thumbs up, thumbs down and no
thumb.  What I'm trying now is to use the "Fix incorrect match" function
within the zero rating autoplaylist.  I figure that those songs might have
been matched to their server copy and thus didn't carry over the ratings
from my library.  Hopefully forcing the upload this way vs. using the match
will fix the issue.  I'll let you know what I find.

**Comment by Jimmyt3477** [comment]
Just wanted to provide an update - the "Fix incorrect match" function fixed this issue.  Apparently when you upload to GPM and the system uses a match instead of actually uploading, it does not carry over the 5 star rating.  Forcing it to do an actual upload ensures the 5 star based rating transfers over.  I was able to quickly find all of the server matched versions by creating an autoplaylist for playcount>0 and Thumb rating of no thumb or thumbs down.

Thanks again for the awesome tool.

**Comment by simon-weber** [comment]
Glad an autoplaylist could help work it out!

Google not importing your ratings on matched tracks definitely sounds like a bug, though according to [an old note of mine on gmusicapi](https://github.com/simon-weber/gmusicapi/blob/bab8e594eb8b900ceadf5df2d6c8a823c56a2a82/gmusicapi/protocol/musicmanager.py#L243) it may have been around for quite some time. Regardless, good thinking to tie it to matched tracks!
