### ISSUE TITLE
"Sync Now" Button

### ISSUE THREAD

**Issue by Dasonk** [simon-weber/Autoplaylists-for-Google-Music#137]
Would it be possible to add a "sync now" button.  I can do a workaround by changing something in my list definition and then changing it back but sometimes I just want the new information (i.e. playcounts) to be applied to the list definition so the list can be updated.

**Comment by simon-weber** [comment]
Sure, that ought to be pretty straightforward.

**Comment by Dasonk** [comment]
Great! That will take away any of my concern about increasing the sync period.

**Comment by simon-weber** [comment]
How would you expect this to interact with periodic syncing? Would you expect it to reset the sync timer (ie, it'd count as having done a periodic sync) or not affect it? I'm leaning towards the latter just because it's easier.

**Comment by Dasonk** [comment]
I'd be fine with either.  My thought would have been that the second option is how it would get implemented since it would be easier since you wouldn't have to muck with resetting the timer.  And at least for me I don't see it causing issues since with the button I'll be increasing the sync period anyways.

**Comment by Noggog** [comment]
Killer.  Thanks!
