### ISSUE TITLE
Thumbs up count doesn't match actual Thumbs Up list

### ISSUE THREAD

**Issue by brianzam** [simon-weber/Autoplaylists-for-Google-Music#138]
I want to create autoplaylists based on my Thumbs Up collection.  The playlist I created has just one one criterion - 'ratings thumbs up' = up.

I have 369 songs in my Thumbs Up collection.  The Autoplaylist I created is only picking up 228.

See screenshots
<img width="790" alt="screen shot 2017-03-12 at 21 48 06" src="https://cloud.githubusercontent.com/assets/3389767/23836292/e5413604-076d-11e7-93fc-9a7322658976.png">
<img width="1008" alt="screen shot 2017-03-12 at 21 49 07" src="https://cloud.githubusercontent.com/assets/3389767/23836293/e541a440-076d-11e7-9e74-d6787d87436d.png">
<img width="950" alt="screen shot 2017-03-12 at 21 49 18" src="https://cloud.githubusercontent.com/assets/3389767/23836294/e548e87c-076d-11e7-8db1-e65386fb5a52.png">

**Comment by brianzam** [comment]
Just seen another post on this #117 with links to add all songs to my library.  that did the trick - it's a work-around so would be good to have this fixed properly.

**Comment by simon-weber** [comment]
Ah, you're referring to https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/119. Yeah, this is something I'd like to fix in the near future; it seems like more people have been running into it lately.

Glad the workaround helped for now!
