### ISSUE TITLE
Support subsorting / multiple sorts

### ISSUE THREAD

**Issue by onespaceman** [simon-weber/Autoplaylists-for-Google-Music#14]
I would like to have an option for subsorting playlists.

Right now if I sort by artist, within that artist the songs are sorted by ID, and if I sort by album, they are not grouped by artist.

What I would like:  
* Artist 1
 * Album 1
 * Album 2
* Artist 2
* ...

I hope this makes sense.  
Thank you.

Edit: also even more subsorting by track number within those albums :)

**Comment by simon-weber** [comment]
Yup, makes sense. Lovefield supports multiple sorts, so we just need to add it to the ui and address https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/9.

**Comment by PeteRepeat77** [comment]
Yeh this would be good for me in cases where the numbers of matching songs exceeds the 1k playlist limit

**Comment by simon-weber** [comment]
Good news: #9 turned out to be an easier fix than I expected. Now that it's out of the way, I should be able to find time to implement this over the long weekend :+1:

**Comment by simon-weber** [comment]
And it only took two months! :sweat_smile: I'll push out a release for this now for yall to try.

This involved a fair amount of changes, so be extra vigilant for things I might have broken in the process.

**Comment by onespaceman** [comment]
Seems to be working great. Thanks!
