### ISSUE TITLE
Reusable Rules

### ISSUE THREAD

**Issue by Noggog** [simon-weber/Autoplaylists-for-Google-Music#142]
Just a feature to put on the bucket list, but it would be neat to be able to construct reusable conditions.  It would just be like we're making an autoplaylist, but just the condition section and name.   We'd then be able to reference those rules in our autoplaylist conditions.

For example, I could make a rule called "Heavy Genre" and have it be an any setup between Metal/Thrash/Rock genre's.   Once that was constructed, I could make an autoplaylist filter on whether the rule "Heavy Genre" is satisfied or not.    This way, Heavy Genre could be updated once easily, and affect multiple playlists.

**Comment by simon-weber** [comment]
Hm, that would be nice. I usually use playlist linking for this, but then I end up with playlists I never really listen to (since they're just used elsewhere).

I don't think it'd be super hard to implement, though I'm not immediately sure where I'd put it in the ui.

**Comment by Noggog** [comment]
I'd imagine it would go under the main Autoplaylists bold header when you first get to the page.  It should list all your autoplaylists, and then underneath that maybe another large bold header of Reusable Conditions.  And then a similar button of "Add Reusable Condition" underneath that would take you to a subpage with just the condition controls?  That's how my brain sees it, at least.

Once that's done, the user can set up several reusable conditions and they'd show up in a list, similar to their list of autoplaylists.

Inside their autoplaylists, then would be another condition type called "Reusable Condition" which would be populated by their defined reusables.

I guess only curveball I see right now is what happens if the user deletes a reusable while it's still being used by an autoplaylist?  I guess it'd either break, or maybe it could just skip that condition as a "pass" if it doesn't exist.  Either way.

Also, I guess if you reuse the same conditions control as the autoplaylist, you'd technically be able to point to reusable conditions inside other reusable conditions.  Lol.   That opens up circular usages, whoops.  It would be a great feature if it was safe and had a circular usage check, I guess.

**Comment by simon-weber** [comment]
Yeah, I think this would pretty much boil down to playlist linking without creating the remote playlist (which already handles the deletion and cycle cases).

**Comment by simon-weber** [comment]
Wow, I hadn't remembered that we had discussed this, haha. I actually just created a new issue after discussion on the mailing list. Merging into https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/165.
