### ISSUE TITLE
ratings are nullable

### ISSUE THREAD

**Issue by PeteRepeat77** [simon-weber/Autoplaylists-for-Google-Music#15]
Regards the rating condition.

The "unrated" rating equals null if the track has never been rated.

Deselecting thumbs up or down to get get rid of a thumbs makes the rating equal 0.

So "unrated" is null and de-rated is 0.... Or maybe use better terminology.

**Comment by PeteRepeat77** [comment]
Now that same track that had a rating "null" now seems to not even have the rating in the query without any changing of rating.

Before if I chose the title condition equals its title, and rating = null it found the track. If I changed the rating = 0 condition the track wasn't found. Now the track doesn't seem to have the rating detail at all.

I'll keep investigating but it may be a few days so thought I would put this out there

**Comment by simon-weber** [comment]
Huh, good find. My first thought is to coerce null ratings to 0, unless you think there's a reason why people would want to distinguish between them in a playlist.

**Comment by PeteRepeat77** [comment]
Originally I thought that turning off a thumbs up (so removing the thumb rating) made it equivalent to 3 star, but it appears not. As it's making them equal 0, I'm happy if they get treated like an unrated song. I wish that a de-rated track was 3 star but that's done at Google's end I guess so. 

I might look into using the star rating again so I can have more than just two ratings.

I'm happy with making null equal 0 as well, as in cases where I remove a thumbs up but I'm not yet to thumbs down and never hear that song again on a playlist, that a De rated rating will still come back when I play my unrated music and let me decide again if I like or don't like. Confused about my explanation... Well not surprised.

**Comment by simon-weber** [comment]
Huh, yeah, I hadn't considered that "de-rating" might be of semantic value.

I'm going to try out the null -> 0 coercion since I think that's what most people expect.

**Comment by simon-weber** [comment]
@PeteRepeat77 ok, the null -> 0 change is in https://github.com/simon-weber/Autoplaylists-for-Google-Music/releases/tag/0.1.2; thanks for bringing it up!
