### ISSUE TITLE
My auto playlist can't have more than 25 titles Oo

### ISSUE THREAD

**Issue by Rakanishuuuu** [simon-weber/Autoplaylists-for-Google-Music#150]
Hey! I'm having something weird and it looks like I'm the only one. I have an autoplaylist limited to 25 tracks max, even if the "test" feature shows me that around 300 titles at least should be included and that I asked the playlist to have 100 tracks max, it's always 25.

I thought my playlist was too complicated so I remade it, really simple: play count less than 20 and not heard since the last 180 days, as you can see here http://i.imgur.com/Tk40mVS.png

When I do the test, he does see more than 300 possible entries: http://i.imgur.com/MlHAYxh.png

But even after trying to sync, it doesn't want to go further than 25 titles. 
Cf: 
http://i.imgur.com/skPyB5f.png
http://i.imgur.com/ZhXQ658.png
It can be less if I change the request, but never more. And a few days ago, the maximum was 28, but I thought it was because I ran out of music not heard recently ^^ 

Do you have any idea why?

Thanks!

**Comment by simon-weber** [comment]
Huh, that's odd; sorry about that. My bet is that the syncing process got stuck, which would explain why things look fine locally but not remotely. [Reloading](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#reloading-the-extension) is a good first step to try for symptoms like this.

If you're still seeing issues after a reload, then [save your logs to a file](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs) and email them to me directly (simon@simonmweber.com). That should give me enough to dig into it for you.

**Comment by Rakanishuuuu** [comment]
Mail with logs sent, thanks for your help!

**Comment by simon-weber** [comment]
Thanks for sending over the logs! This seems like the same symptoms as https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/135 (which unfortunately we never figured out). So, we'll have to restart the same debugging process.

First, a quick question: do you have a subscription account? Or does your library only contain uploaded music?

Let's also test to see if the non-syncing tracks are of a particular type:
* add the condition "type doesn't equal -1" to the playlist, then test it. The same number of tracks should appear, but the type column should show up.
* click on the type header to sort by it, then note the type of the tracks that sync (you may need to search for it) and the type of tracks that don't sync. Are there any patterns?

Lastly, let's see if Google's responses have any extra information:
* [open the logs](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs) as before
* click the "network" tab.
* ensure filters are off and recording is enabled, then wait for a sync. A few rows should appear.
* right-click the row with "plentriesbatch" in it (not "playlistbatch"), then hit "copy > copy response". It should start with `{"mutate_response":[{"id":"...`
* send the contents to me (either email or here is fine; there's nothing sensitive in it).

Hopefully one of these will point us in the right direction!

**Comment by Rakanishuuuu** [comment]
"First, a quick question: do you have a subscription account? Or does your library only contain uploaded music?"
No, I don't have a subscription account (the monthly thing is a bit much for me, but if there is a way to donate, I'm in btw :D).
No, I must have like 50% of uploaded music. My account started with only uploaded music but it was a few years ago, and I've added albums since (or even removed uploaded music and replaced it with albums directly from Google Play, as the quality was way better).

"click on the type header to sort by it, then note the type of the tracks that sync (you may need to search for it) and the type of tracks that don't sync. Are there any patterns?"

I always have types 2, 6 and 7. I tried with 2 playlists, one with around 150 tracks possible, the other with around 4000, those are the only types my playlist have. 

I also checked in the "test" feature. The playlist with 150 possibilities only offered types 2, 6 and 7. The bigger one (4000 possible titles) had 2 titles type 1. If I remember well, those 2 tracks were offered for free when I subscribed and I clicked at the time "Add to my account" out of curiosity.  Otherwise, only types 2 6 and 7.

Done the log thing! Here is what the plentriesbatch says:
https://pastebin.com/aMLKpRQD


Oh and just in case, that's my "real" autoplaylist. Maybe it was too complex and I broke the extension ^^ 
http://i.imgur.com/QO3rfqO.png
I can copy paste the "comment" thing of the playlist, but I have too many requests, it stops ^^

((play count less than or equal 20 and (rating thumb doesn't equal "down" and last played earlier than "20 days ago")) or (playlist is equal to "Envies du moment" and last played earlier than "2 days ago") or (rating thumb equals "up" and play count less than or equal 60 and last played earlier than "60 days ago") or (playlist is equal to "Récents custom" and play count less than or equal 5) or (date added to library betw



Hope we'll find something :D

**Comment by simon-weber** [comment]
Woah, ok, so the `TOO_MANY_ITEMS` responses are definitely the problem, but I'm not sure why we're seeing them. I've only seen them when attempting to add tracks beyond the 1k playlist entry limit.

For that request, how many entries did Google's playlist have, and how many did the extension want it to have (ie, what did "test" come back with)? I'd be really surprised to see this from a small playlist (like the 25-remote, 300-desired one from earlier), especially considering there were only 77 attempted changes in that response.

I wouldn't worry about the complexity of the autoplaylist definition as long as running "test" works as expected.

**Comment by Rakanishuuuu** [comment]
Not sure to understand your question, sorry in advance!

In the request, I ask for a playlist of 100 tracks. 
The test sees 407 entries.
My generated playlist is 25 tracks ^^

**Comment by Rakanishuuuu** [comment]
Addition: just limited the automatic playlist to 24, 25 and then 26 tracks max.
24 tracks: https://pastebin.com/V5xQNrgx (it generated me a playlist of 23 tracks. Last line says "too many items)
25 tracks: https://pastebin.com/yPCRHWU5 (it generated me a playlist of 24 tracks. Last line says "too many items")
26 tracks: https://pastebin.com/CQmHGMZg (it's a very short error compared to last time)

**Comment by simon-weber** [comment]
Huh. I've got a few theories, but none are particularly strong:
* there's a bug on Google's end: they think the playlist is bigger than it actually is, so they're rejecting our adds.
* the type 7 tracks are causing problems: type 7 == subscription tracks, but you're on a free account. Maybe these are filling up the playlist without being visible in the UI?
* the type 1 tracks are causing problems: free tracks may require adding with a different id (like subscription tracks do).

Here's a few tests to narrow it down:
* delete a broken autoplaylist and recreate it: this recreates the underlying Google playlist, which should clear out any broken state on their end
* create a new autoplaylist with condition "type equals 1": are any tracks missing?
* create a new autoplaylist with condition "type equals 2": are any tracks missing?
* create a new autoplaylist with condition "type equals 6": are any tracks missing?
* create a new autoplaylist with condition "type equals 7": are any tracks missing?
* if you recreate the TOO_MANY_ITEMS response, try to also copy the request body in addition to the response body (so we can see if there's any pattern to which ids are returning the error)

**Comment by Rakanishuuuu** [comment]
"the type 7 tracks are causing problems: type 7 == subscription tracks, but you're on a free account. Maybe these are filling up the playlist without being visible in the UI?"

Oh sorry, when you asked about the subscription, I thought you were talking about your extension :D I am a subscriber to Google Music since a few years!

I'll do your tests soon! I was wondering if removing the extension and reinstalling it again would fix anything, but doesn't seem to be the case then.

**Comment by simon-weber** [comment]
Interesting. Yeah, it definitely sounds like something weird happened on Google's end.

I'll close this since it sounds like a fluke, but I'm happy to reopen if you or someone else runs into it again.
