### ISSUE TITLE
Playlist created but not filled

### ISSUE THREAD

**Issue by gregsdennis** [simon-weber/Autoplaylists-for-Google-Music#152]
I can't get my playlist to fill with songs.  The definition I'd like is any song that's not in either of two other playlists, limiting to 250 songs.

When I test with any "playlist" setting, I get no results.

Even having no filter settings (but still the limit) adds nothing to the playlist.

(Using the free version of the plugin.)

---

Not sure if it's related, but I'm getting this error in the debug window:

    GET chrome-extension://blbompphddfibggfmmfcgjjoadebinem/css/DataTables-1.10.12/images/sort_both.png net::ERR_FILE_NOT_FOUND

This occurs when the test results popup appears.

**Comment by simon-weber** [comment]
So when you create an autoplaylist definition with no rules at all and hit test, you get 0 results, right? If that's the case, something probably went wrong when pulling in your library. Try [reloading the extension](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#reloading-the-extension) and see if that fixes it for you.

**Comment by gregsdennis** [comment]
That fixed the filling problem.  Thanks.

The "file not found" error still happens, but it doesn't seem to be affecting anything functionally.

**Comment by simon-weber** [comment]
Great!

I probably just botched the vendoring of datatables to cause the other one. It should just be a ui quirk.
