### ISSUE TITLE
Ability to sort based on time based conditions

### ISSUE THREAD

**Issue by faulkj** [simon-weber/Autoplaylists-for-Google-Music#154]
I would like to be able to do sorting that only applies to things that happened within the timeframe specified by the Last Played conditions.  For instance, I would like to create a playlist of the songs that I've played the most just within the past 30 days.  Or just the songs that I've like within the past week.  As far as I can tell, it's not currently possible.. 

Now that I'm thinking about it, though, I suppose that Google's API probably doesn't provide the discreet timestamps you'd need to do such filtering.  Am I right?

**Comment by simon-weber** [comment]
You're right, unfortunately: the event-based metadata Google provides is always aggregated in some way, eg into a sum (like playcount, which we only see over all time) or max (like last played, which we only see the most recent occurrence of). As far as I know, there's no straightforward way to get the data you're looking for: Google themselves probably don't store it after aggregating it.

Sorry to be the bearer of bad news! I'd love access to this kind of stuff too, so I'll be sure to keep an eye out for it in the off chance Google exposes it later on.
