### ISSUE TITLE
cannot add new autoplaylists

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/Autoplaylists-for-Google-Music#156]
Originally reported this in https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/78#issuecomment-306046616:

> My issue is I can no longer add new playlists.
> 
> I can delete playlists, and that syncs fine.
> I can modify existing playlists, and that syncs fine.
> I can no longer add any new playlists. They just don't show up.
> 
> I have 2 pc's and an adroid, so possibly ran simultaneously on chrome in 2 locations.
> 
> Any ideas how to fix this?

@bryanjmckinnon, give this a shot and see if it works:
* [reload the extension](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#reloading-the-extension)
* open the extension and create a new autoplaylist
* wait 30 seconds, then refresh your Google Music tab

**Comment by bryanjmckinnon** [comment]
The suggestion above (reload the extension etc) did not solve my problem.

This problem has persisted over 1 month.
I have 40ish playlists. The bottom 3 on my list in the extension are not showing up in google play (and I've hit TEST and a list exists in theory but not on my google play.

b

**Comment by simon-weber** [comment]
Hm, ok. Do you remember if any of your not-syncing autoplaylists "disappeared" (ie, you created them and then they went away)? Or were all of them attempts to create a playlist that then never showed up?

Either way, I've got a few ideas to try:
* try creating a normal playlist directly in Google Music. Does it show up as expected? This will test for general problems on Google's backend.
* navigate to https://play.google.com/music/listen#/accountsettings and hit "refresh library". Afterwards a) do any missing playlists show up, or b) you can now create autoplaylists successfully? This will test for problems on Google's frontend.
* reload the extension, create a new autoplaylist, check that it doesn't show up, then [export your logs to a file](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs) and email them to me directly (simon@simonmweber.com). This may point us towards why creations are failing (though we may end up needing more detailed information from the network tab).

**Comment by simon-weber** [comment]
Any luck with this?

**Comment by simon-weber** [comment]
I haven't heard back in a bit, so I'm going to close this. Feel free to leave a comment if this is still an issue and we can look back into it.

**Comment by bryanjmckinnon** [comment]
Hey, sorry for delay. I went away for summer.

I have 43 playlists that I created. I have not been able to create any new
playlists since earlier this year.

b

**Comment by simon-weber** [comment]
Welcome back! Can you run through the debugging steps in https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/156#issuecomment-306075841 and let me know how they go?

**Comment by bryanjmckinnon** [comment]
FIXED!

Hitting REFRESH in AccountSettings and then adding a new playlist seems to have fixed the problem.

I'll continue to monitor.

Thanks so much! I really love the service. 

bryan

**Comment by simon-weber** [comment]
Glad to hear it!
