### ISSUE TITLE
Temporarily Unopenable Playlists on startup

### ISSUE THREAD

**Issue by Noggog** [simon-weber/Autoplaylists-for-Google-Music#158]
Seems to be less severe and a little different in behavior.  I've noticed it for at least a few weeks?

I usually see it when I first open Google Play for the day.  I've noticed that right as I open it, the playlists sync near immediately, almost as if some code is recognizing they haven't been synced in a long time.  This works a good portion of the time, but on occasion it -seems- to kick it into that "cannot open playlist" mode we had problems with before.

Fortunately, if I just leave things open (usually i'll just play stuff without my playlists for a while), it recovers within the hour.

Not terrible overall, but something I thought you should be aware of. 8)

I do have the enable change batching experimental boolean on.  I've the same setup as before, several playlists with ~600 songs a piece.

**Comment by simon-weber** [comment]
Cool, thanks for letting me know. Yeah, this is probably a side effect of all the changes being applied at once. Throttling updates on startup might help with this, though it would mean playlists are out of date more often.

**Comment by Noggog** [comment]
Just reporting in a bit more. Nothing has changed on my end as far as playlist definitions go for a while.
 
This last week it was pretty bad, was out for 4ish days with unopenable playlists in the browser.
Today they finally came back and were usable, and I noticed something odd.  The playlist had 966 songs in it, while the spec said it should be filled with 500.   I did a "sync now" and it filled with a new list and only had 500 songs again.

The fact that the playlist finally came out of its shell and had 966 songs seems odd to me, and maybe a clue of what's going on.  How would a playlist get more songs than what was specified?

Anyhoo, going to do an experiment of turning my sync period to OFF, and just doing Sync Now myself and see how that goes for a bit.  Will keep you posted

**Comment by simon-weber** [comment]
> The playlist had 966 songs in it, while the spec said it should be filled with 500. I did a "sync now" and it filled with a new list and only had 500 songs again.

Yeah, that's odd. I'd be surprised if that was something on our end, since the extension submits deletes and additions together (so it's unlikely that the deletes would fail while the adds succeed). Probably that's just an artifact of whatever Google system catching up.

> Anyhoo, going to do an experiment of turning my sync period to OFF, and just doing Sync Now myself

Cool; let me know.

**Comment by simon-weber** [comment]
This issue has gone stale so I'm going to close it out. Let me know if you're still seeing problems and I'll look back into it!
