### ISSUE TITLE
performance problems and duplicate tracks when updating playlists

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/Autoplaylists-for-Google-Music#17]
From https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/10#issuecomment-160217366, @johnrobertlawson says:

>
So after creating a playlist, there's a few minutes of flux where the webpage is not responsive and there a lots of duplicates, but afterwards the playlist is fixed. However, the page still refreshes every minute or so and locks up temporarily, presumably as the script is checking the remote playlist?

**Comment by simon-weber** [comment]
Can you grab the background script logs? A single sync should only lock Google's ui for a second or so. My ideas are:
* we ran into the race condition between periodic and manual syncs, and the two are messing with eachother
* there's a bug with the sync logic

**Comment by johnrobertlawson** [comment]
OK, it's currently looping this over and over (any idea how to preserve line breaks in Markdown?):

```load response [Array[3], Array[1]]0: Array[3]1: Array[1]length: 2__proto__: Array[0]
googlemusic.js:228 no need to delete; adding
googlemusic.js:162 adding 69
googlemusic.js:171 add response [Array[3], Array[2]]
background.js:131 not a 0-track add; retrying syncPlaylist [Array[3], Array[2]]
background.js:28 index for 07953966069546500216 0
background.js:100 syncPlaylist, attempt 7
background.js:118  found 1000
background.js:120 first is Object {id: "0009efee-cdbd-3d61-b103-aa6295687f7b", title: "Monoliths", artist: "Maserati", album: "Passages", albumArtist: ""…}```

**Comment by simon-weber** [comment]
(I edited to put the triple-backticks on their own line, which fixed the formatting problems.)

Normally the sync process converges after a few rounds of adding/deleting. It looks like there's something going on where it doesn't see those 69 tracks even after adding them a few times.

Let's try to isolate these tracks (maybe there's something odd about them, like the type 7 AA tracks). 
* we can find the track ids we're sending in the network tab, then test a playlist with `id, equals, "the id"` to get it's information
* expanding the "add response" array might be useful. For successful requests it should contain the ids that we sent Google.

Or, if you'd like, swing by the [gmusicapi irc](http://webchat.freenode.net/?channels=gmusicapi), mention my username, and we can pair on it.

**Comment by simon-weber** [comment]
Uninstalling and reinstalling seems to have fixed this. Feel free to reopen if it happens again.
