### ISSUE TITLE
Not all songs in a playlist are actually added in Google Play

### ISSUE THREAD

**Issue by hoopahmadness** [simon-weber/Autoplaylists-for-Google-Music#174]
<img width="193" alt="screen shot 2017-11-13 at 10 27 11 am" src="https://user-images.githubusercontent.com/7513897/32736522-481889f2-c85d-11e7-9eb1-1f6925fd2550.png">
<img width="340" alt="screen shot 2017-11-13 at 10 26 57 am" src="https://user-images.githubusercontent.com/7513897/32736524-4833688a-c85d-11e7-907c-df7c64234ba5.png">

Even though the playlist definition is catching all these songs, only a subset of those songs are actually being saved to the playlist in Google Music. I've consistently had 116 songs over the past few weeks. I am not able to find a pattern in what is being added or not added.

I'm willing to participate in debugging and troubleshooting. I'm using the free version so this is my only playlist.

**Comment by hoopahmadness** [comment]
Update: I've deleted the playlist from Google, expecting it to reappear when Autoplaylists syncs. It has not done so.

**Comment by simon-weber** [comment]
Hm, that's odd. Is it possible that there are duplicates in the list shown by Autoplaylists? I think if you had uploaded and bought/matched/added-via-subscription the same track that Autoplaylists will show both but only add one, but that seems like a pretty out-there case.

Here's a handful of more general debugging ideas:
* try deleting the autoplaylist (not just Google's copy) and then recreating it: the local and remote state might have gotten out of sync after deleting Google's copy
* if that doesn't work, [reload the extension](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#reloading-the-extension), then manually trigger a sync ("sync now"): that'll fix up anything relating to the cache being corrupted
* if that still doesn't work, [open your logs](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs), clear them, manually trigger a sync, then export them to a file and email them to me

**Comment by hoopahmadness** [comment]
I've emailed you a log. While I'm waiting, I think I'll uninstall try to start from there.

**Comment by simon-weber** [comment]
Glad to hear it! I usually don't recommend reinstalling since that wipes out all your local state, but it was a good call in your case: the extension was rejecting syncs for that playlist since the remote playlist was gone. Someday I'll get around to improving that situation (it's tracked in https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/160).

No leads on why the problem happened originally, though. Definitely get back in touch if it happens again!
