### ISSUE TITLE
Unable to reliably read existing playlists?

### ISSUE THREAD

**Issue by eldorel** [simon-weber/Autoplaylists-for-Google-Music#181]
Ok, I've tried several different things, and none work as expected. 

My goal is to create an autoplaylist that uses several existing playlists, and skips over tracks that I've thumbed down.

Initially, I created a playlist with two rules 
{playlist is equal to: "90's radio random" }
{Rating thumb does not contain: Down}

Hitting the test button resulted in no songs. So I started experimenting. 

I've created this test autoplaylist: 

[Test 1](https://play.google.com/music/playlist/AMaBXymoTmY-gxw2Qbn3pL6z0GvrkwNDmBSlH3AFOge5MSrJaDE1ZNQSB9PkXDHIx3DIt3E0qrOP5FkPdu2vKlDXHLISd6CBew%3D%3D)

(Synced 1/1/2018, 1:57:01 PM by Autoplaylists for Google Music™ to contain: playlist is equal to "90's_radio-random" sorted by: album ascending.)

Unless I am mistaken, this should have resulted in a mirrored copy of my original playlist. 
Note:  the ONLY change from defaults is to add a single rule : "is in this other playlist"

And here is the original playlist. 
[Original](https://play.google.com/music/playlist/AMaBXynMb9LfkLF04MrsH_A26DyZu7NNsLF8z959uY9vjCb1mFheWUuUkQ5Un_B6kc6gYJgBxrfAqvjfHpAEYHHxcJH7_m87xg%3D%3D)

As you can see, the Autoplaylist has only 18 tracks, while the original playlist contains 60. 

Additionally, most of my other playlists return NO tracks when used as a rule. 

[Original:](https://play.google.com/music/playlist/AMaBXyl2OwgkztZJ1PWHq1i8xnkRSDvvC7qNqYuUh7BdJ0Ll0XUD5qjn3S92hJZRIsWkxEyk5BTu7ggGyJOd02H7hCsBJgnV2g%3D%3D)

[Test:](https://play.google.com/music/playlist/AMaBXylGx2T4X8PLkhX8-dSRUv4AQHp34DHM_rNpTgU2xpwMfJn-U2qreQxkeavfPei731Ku-b0haPuNR2-kNOGDdT8_btzhiw%3D%3D)

(Synced 1/1/2018, 2:03:13 PM by Autoplaylists for Google Music™ to contain: playlist is equal to "Violins from hell" sorted by: album ascending.)

**Comment by simon-weber** [comment]
My first guess is https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/119, which should be easy to test: make sure everything in 90's_radio... is added to your library.

Let me know how that goes and we'll dig into the more complicated stuff if needed.

**Comment by eldorel** [comment]
Nope, Looks like that was it. 

Sadly, that means that the autoplaylist is nearly useless for my use case.  

I was trying to avoid having to manually click on thumbed down tracks and remove them from the playlists. 
It takes forever, since google insists on refreshing the page every time you  add or remove a track from the list.

Having to manually click on every single track to add them to the library is just as bad if not worse.

So, unless there's a fast way to add an entire playlist to library that I'm not seeing, I'm just going to cancel my Play Music subscription and go back to manually managing my own library and syncing it between devices...

**Comment by simon-weber** [comment]
Ah, there's a way to batch add to library but it's a bit hidden away:
* click one track to select it
* select another track by shift-clicking the track below it (or control/command clicking it)
* in the top left, click the "2 selected" dropdown then hit "select all"
* right-click any track, then hit add to library

I think this will work even if there are library tracks in the selected list (though I can't easily test it since I don't have a subscription account).

**Comment by eldorel** [comment]
I can confirm that these steps work. 

Thank you very much.

**Comment by simon-weber** [comment]
Glad to hear it and sorry for the trouble! I hope to have a better fix for this eventually.
