### ISSUE TITLE
Clicking on the icon in the extension bar does nothing when the page is loaded

### ISSUE THREAD

**Issue by asamson23** [simon-weber/Autoplaylists-for-Google-Music#182]

**Comment by simon-weber** [comment]
Is the icon greyed out or black?

Either way, reloading that sounds like a good bet: https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#reloading-the-extension. If that doesn't work, send me your logs and I'll look into it.

**Comment by asamson23** [comment]
The icon was black.

I discovered that when you click on the icon, there is a popunder window that asks for a login, which is why I wasn't able to do anything with the extension.

**Comment by simon-weber** [comment]
Huh, there's nothing in the extension like that. Did you find another extension causing it?

**Comment by asamson23** [comment]
Nope, since it was the only extension I installed today. It might also be caused by the fact that I built it from your repo.

**Comment by simon-weber** [comment]
Ah, are you seeing a Google OAuth prompt? Usually it shows as part of the welcome prompt after installation, but you might have bypassed that by building it manually.

If it is then that does sound like normal behavior: if the extension doesn't have permissions, it'll do an interactive check when clicking the page action.

**Comment by asamson23** [comment]
That might have been it with the window, because it was a Google Auth prompt.
