### ISSUE TITLE
Rating Songs 

### ISSUE THREAD

**Issue by rprigge** [simon-weber/Autoplaylists-for-Google-Music#183]
I don't know where to post this, so I figure that I will put it here.  I used iTunes for many eons and had a very sophisticated structure built around 1-5 star ratings for my songs.  When I migrated to Google Play Music for misc reasons I really struggled.  I had searched for ways to add star ratings and didn't see anything under google music or AutoPlaylists for google music. 

At the end of the day, I have been able to accomplish what I wanted to.  For me the Disc Number metadata is pretty useless so I decided to convert the Disc Number to be my star rating.  I went into my library and changed the disc number to be my 2-5 star rating.  (Most of my disc numbers are blank or a 1 so my searches ignore less than 2 as I dont want to modify 40k songs) I then built a bunch of playlists off of disc number.  What is great is that autoplaylists allow you to search on disc number with greater than as well as greater than or equal to.  Anyway, I didn't see anyone using Autoplaylists in this way and it solved a gigantic issue for me...

Autoplaylists is phenomenal and has solved so many problems...

REP

**Comment by simon-weber** [comment]
Clever workaround! Glad to hear Autoplaylists gives you that flexibility.

Back in the day there was a lab to opt in to 5 star ratings - which is why there's still references to it in Autoplaylists - but Google's since removed it, unfortunately.
