### ISSUE TITLE
Playlist Not Filling To Desired Amount

### ISSUE THREAD

**Issue by Noggog** [simon-weber/Autoplaylists-for-Google-Music#185]
Small issue that I thought I'd bring up:

My playlists seem to not be filling to their desired capacity.   I have some simple playlists such as:
- Rating not down
- Last played earlier than 150 days
- Random ascending
- Limit 900

The results are as I want them, except it just fills it some smaller amount songs, instead of 900.  Seems to be consistently doing so, as well.  So far it's been fine since usually it's enough to get me by, but it's curious enough to report.

One of my playlists is filled to 230 right now, while another is about 650.  I haven't been able to narrow down a pattern aside from the lists stay at their numbers; I just restarted now and resynced and they stayed at those capacities with different songs.

**Comment by Noggog** [comment]
So i made a duplicate, as well as a new playlist:
- Original playlist has 212 / 900 
- Duplicate has 866 / 900
- New playlist has 582 / 600

Hard to see a pattern, other than the duplicate and the new playlist having ~96-97%.

The original seems to be sticking around the 210 area, despite random resets (thanks!) and resyncs.

**Comment by Noggog** [comment]
Another thing I've noticed is the new syncing "progress wave" never finishes.  Just stays syncing indefinitely.  Not sure if that's an indication of something wrong, or if that's just an edge case that hasn't been handled so it just shows forever

**Comment by vokinpirks** [comment]
liked
My playlist
Synced 6/18/2018, 7:15:42 PM by Autoplaylists for Google Music™ to contain: (rating equals 5 or rating equals 4 or rating thumb equals "up") sorted by: .
684 songs•89:13:58

Thumbs up
Auto-playlist
Songs rated with a thumbs up are automatically added to this playlist.
753 songs•98:09:26

753 - 684 = 7=69 songs are missing

**Comment by simon-weber** [comment]
Ah, ok, that sounds like classic overloading symptoms to me. Should be able to see if that's the case by turning off periodic syncing for a few days, then coming back and syncing one of the playlists manually.

> Another thing I've noticed is the new syncing "progress wave" never finishes

Oops. I hacked that together by waiting for the last sync to register, but forgot to actually do anything when it times out. Easy enough fix.

**Comment by Noggog** [comment]
I've already got periodic turned off; I usually manually sync every morning when spinning things up.

I'll try doing just one playlist tomorrow and report

**Comment by Noggog** [comment]
Came in this morning and tried to sync a single playlist.  I did this by opening the settings panel, clicking on the single playlist, and hitting save.  It did not seem to improve the amount that was put into it: it filled with 205/900.

**Comment by simon-weber** [comment]
Gotcha. Can you [email me your logs](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs) after your next sync when you have a chance? I have a feeling they'll just show errors from Google, but it's worth double checking.

**Comment by Noggog** [comment]
Shipped some logs over.  Didn't see any error spam with my quick uneducated glance.
The logs didn't seem to save any dropdown data underneath that top layer, so let me know if you want me to drill down and get some of that.

The sync that triggered those logs filled 195/900

**Comment by Noggog** [comment]
It does give me the feeling that the smaller sizes are systematic or persisted.   I've never seen a higher count in recent times on that playlist, and a copy of it immediately has (near) max.   I suspect a clone will slowly decrease as its resynced, though, or maybe some event will happen that will cut it down permanently to a low level like the original.  That's all just my gut though

**Comment by simon-weber** [comment]
Hm. Can you try expanding the responses for the line that looks like 
```
finished sync {action: "update", userId: "15722017326388160920", localId: "1489773879742"} . responses (2) [{…}, {…}]
```

Alternatively you can save the whole request/response [from the network tab](https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/10#issuecomment-160188760).

**Comment by Noggog** [comment]
Sent another log.  I see your codeCounts, which has a response of "TOO_MANY_ITEMS:190, "OK":55

**Comment by simon-weber** [comment]
Heads up that I'm moving this into a new issue so I can combine multiple threads: #193.
