### ISSUE TITLE
Sync not happening at set times, "Sync all playlists button" not working

### ISSUE THREAD

**Issue by confidentjohn** [simon-weber/Autoplaylists-for-Google-Music#187]
Hi

Over the past few days Synching seems to have fallen over somewhat.

I usually have periodic sync set to every 120 minutes, this has not been happening as expected.

Also selecting the sync button doesnt do anything.

I have disabled/enabled the extension, this hasnt done much.

I did last night start from scratch, the initial sync happened, but no subsequent syncs have happened.

I have also attempted to sync individual playlists, but this has also stopped working.

Anythoughts? any thing i can send to help debug.

**Comment by simon-weber** [comment]
Hm. Normally I'd expect a reload to fix that kind of issue.

Can you [send over your logs](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs) from when you're in that state? It'd also be good to have an example of hitting the sync button in them too.

**Comment by confidentjohn** [comment]
Its started working now, im really sorry to have wasted any time. But the last 2 days its back up and running.

I wonder if there was an incremental chrome update or something that knocked it out.

I'll keep an eye on it, and if it repeats i'll upload logs.

Thanks for the reply, also, thanks for the extension i use it everyday.

**Comment by simon-weber** [comment]
Glad to hear it! Don't hesitate to reach out if it happens again.
