### ISSUE TITLE
Comment conndition not working with mp3s

### ISSUE THREAD

**Issue by Jaapdl** [simon-weber/Autoplaylists-for-Google-Music#194]
Hi,

i want to add all songs that contain a specific comment to a playlist but only a very little part of my library that is in m4a format works with the condition. Every mp3 seems to be not recognized.
Unfortunately most of my smart playlist in iTunes are created by the comment metadata.

Hope you can address this issue. 

Cheers
Stefan

**Comment by simon-weber** [comment]
Hey there! My best guess would be that the format is a red herring. Here's some ideas to try:
* if you [open the debug interface](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#manually-making-queries) and click run without making changes, then type the title of some of the mp3s into the search bar, are you able to find them?
* if you're able to find one, click the "csv" button and open the resulting file. That will have the full metadata of the song as seen by Google, which might show what's preventing the match (maybe leading or trailing whitespace in the comment).
* if you're not able to find any in the debug interface, they may be in a playlist but not in your library. Try finding them in Google Music, right clicking, and seeing if you get the "add to library prompt". If you do, the easiest fix is to add them all.

Let me know how it goes!

**Comment by Jaapdl** [comment]
Hey Simon,

I could find a track that should match the criteria but the comment was not included in the csv file.

**Comment by simon-weber** [comment]
Interesting. So it was just an empty string in the csv, right? And if you open the same track in Google Music, you able to see the comment?

**Comment by Jaapdl** [comment]
It was not empty, i just couldn't find the comment in there. If you want i can post the content of the csv file here.

I am not sure where i should see the comment in Google Music. When i right click on a file and click on edit details i cannot even see a comment on those files that work (those in m4a format).

**Comment by simon-weber** [comment]
Sure, feel free to post it here.

To see comments in Google Music, you may need to enable the "lab" for it. That's under settings > labs > "view track comments". I think this link will bring you there: https://play.google.com/music/listen?#/accountsettings.

**Comment by Jaapdl** [comment]
Okay, as i supposed the comment section is only filled for those few m4a tracks, the mp3 files don't have a comment in the Google Music Library.

**Comment by simon-weber** [comment]
Gotcha. I think you should be able to batch edit that field in Google Music by selecting multiple tracks and editing them at once.

Once the comment is in there, Autoplaylists should pick it up on the next sync.

**Comment by Jaapdl** [comment]
Yeah, i guess i need to find a way to write itunes comments into the id3 tags of the files so that Google Music also sees those comments.

**Comment by simon-weber** [comment]
Gotcha. I'm gonna close this since we figured out the autoplaylists side of things -- feel free to reach out if I can help.
