### ISSUE TITLE
Clicking on the small icon to the right of the url does nothing

### ISSUE THREAD

**Issue by mvaldellon** [simon-weber/Autoplaylists-for-Google-Music#196]
Tried uninstalling and reinstalling. No luck. Unable to create new playlist, view current playlists, or sync current playlists.

**Comment by simon-weber** [comment]
Hm. Can you email me [your logs](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs)? The icon not showing up is peculiar; unless something changed about Google's url, it means something's wrong very early on (maybe related to auth).

**Comment by mvaldellon** [comment]
Hi,

I reinstalled the extension and refreshed Play Music. Works now, but had to
recreate my playlists.

Thanks.

**Comment by simon-weber** [comment]
Ah, good to hear. Sorry you had to recreate your playlists, though!
