### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by domramsey** [simon-weber/Autoplaylists-for-Google-Music#197]
I've been using Autoplaylists for some time, but it's recently stopped working entirely. I can't pinpoint exactly when.

Clicking the icon while in Google Play Music no longer loads the extension but now, after several seconds I get a pop-up window containing the Google Admin console for my domain. 

Tried it on multiple platforms (Mac, Linux & PC) with multiple versions of Chrome and Chromium but none of them work any more.

**Comment by simon-weber** [comment]
Huh, I wonder if there's something odd going on for GSuite users. Everything has been normal for me recently, and I haven't noticed anything strange in my error reporting.

Can you [email me your logs](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs)? I'll see what I can find out.

**Comment by simon-weber** [comment]
We talked briefly off-thread: this was definitely happening, but I don't have any good theories why. It looks like a chrome bug to me.

Going to close for now. Let me know if anything changes.
