### ISSUE TITLE
Only 3 songs when I expected at least 100

### ISSUE THREAD

**Issue by hiddenshallows** [simon-weber/Autoplaylists-for-Google-Music#198]
Tried to make a playlist of all songs I thumbed up with a release year of 2018 and got a result of just 3 songs when I know there are at least 100. Would've made my day if this worked.

**Comment by simon-weber** [comment]
When you test the autoplaylist, how many do you get? If it's less than expected, we'll probably just have to tweak the query a bit to get it working.

If you see the expected result when testing it, we can look into why syncing isn't working properly.

**Comment by simon-weber** [comment]
Great, that should be an easier case to check.

One quick thing to check: if you have a subscription account, are the songs you're expecting to see added to your library (ie, if you right click, do you get the option to add them)? If they're not, the easiest fix is to add them. More on that in https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/119.

If they're already added, try [these instructions](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#manually-making-queries), then hit "run" without making any changes. That'll show you you entire library from the extension's perspective. Then, you can try searching for the tracks that are missing, and add the thumbs up + release year columns to see exactly what their metadata is.

**Comment by hiddenshallows** [comment]
Ah! Okay, everything has to be added to library! That sounds like where I was going wrong. don't have access to my laptop right now but will try that.

I don't have a subscription account and my week trial ran out a few days ago. 

I will check that out. Thanks. Will definitely be subscribing if I get this working. I've missed smart playlists.

**Comment by simon-weber** [comment]
Sounds good! Let me know how it goes.

**Comment by simon-weber** [comment]
How'd it work out?

**Comment by hiddenshallows** [comment]
yeah it worked thanks! just needed to add everything to library first. duh. just was a bit of a pain going through every playlist and selecting all and adding to library as Google keeps giving me errors when I do that. so I have to try selecting fewer tracks and going through maybe 100 at a time. so I kinda gave up on the idea of adding everything in every playlist to library. but I did get all the relevant ones added for that 2018 thumbs up playlist to work so that's awesome. thanks!

**Comment by simon-weber** [comment]
Good to hear! If I get a chance I'll look into a way to make that process easier.
