### ISSUE TITLE
Playlist with thumbs up criteria includes songs that don't have it

### ISSUE THREAD

**Issue by spookypeanut** [simon-weber/Autoplaylists-for-Google-Music#199]
My conditions for my playlist are this:
Synced 09/01/2019, 19:25:52 by Autoplaylists for Google Music™ to contain: (rating thumb equals "up" and playlist is not equal to "Thumbs up without subscription") sorted by: .

And yet a couple of songs in the playlist do not have thumbs up (and I haven't changed them recently).

Any idea what happened?

**Comment by simon-weber** [comment]
Hm. When you hit use test button in the extension, do the songs there match what you're seeing on Google's end?

**Comment by spookypeanut** [comment]
They do match, but a couple of the tracks show as having thumbs up in the
test window, whereas they don't in google music. It's possible they have
had a thumbs up in the past, could that be confusing things?

**Comment by simon-weber** [comment]
Hm. This is a long shot, but did you use the 5-star rating lab in the past? I've seen some strange handling of those after Google converted everything to thumb ratings.

If so, you may be able to fix it by rating them, waiting for Google to sync them, then unrating them again.

**Comment by spookypeanut** [comment]
I did, but I'd be surprised if I did for these particular tracks. However,
I tried, and it seemed to fix it. Thanks!

**Comment by simon-weber** [comment]
Glad to hear it!
