### ISSUE TITLE
Sync all fails (Saves work); Test sorts in order, GPM playlists not in order

### ISSUE THREAD

**Issue by NJosephLee** [simon-weber/Autoplaylists-for-Google-Music#201]
**All syncs fail:**

![image](https://user-images.githubusercontent.com/48372079/54065282-920e2a80-41ec-11e9-837b-b0db2fb87384.png)

I've tried reloading the extension, and resetting authorization code. Reloading auth code changed the errors but not the outcome.

All playlist descriptions change to the new sync time on Google Play, although I don't wish to scan through all the playlists to see if everything actually synced properly.

Change batching does not affect this.

(I do use a VPN, if that makes any difference, however having it enabled versus disabled didn't seem to have any impacts.)

**Test sorts in order, GPM playlists out of order:**

saving playlists to sync them are successful, however do not appear in the correct order on Google's end:

![image](https://user-images.githubusercontent.com/48372079/54065522-03031180-41f0-11e9-8381-e0870f09cbd2.png)

![image](https://user-images.githubusercontent.com/48372079/54065512-f383c880-41ef-11e9-9ae4-322752da06a5.png)

Deleting the playlist on google play, and the playlist definition, then remaking the autoplaylist and resyncing yielded the same result.

Songs are in correct order in small batches yet the batches themselves are out of order.
Having change batching enabled has occasionally shifted the positioning of these batches versus if it's off.

Thanks in advance for taking a look! I hope to have these issues resolved, as smart playlists are essential for me and I don't want to go back to *Apple Music* ***shudders***

PS: I was able to find a way around the backoffMins restriction without altering any coding. If you were unaware of this bypassing method, I can elaborate in a PM.

**Comment by simon-weber** [comment]
I checked my metrics and don't see anything awry, so my guess is this is just some account-specific overloading. I'd recommend turning on change batching, then disabling periodic syncing and waiting a day or two before trying again -- it can take a surprisingly long time for their end to recover. There's some more details [here](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#handling-syncing-failures-or-an-overloaded-account) (though it sounds like you've probably already looked at that page).

I'm not concerned about folks getting around the backoff timing, so feel free to note that here too if you'd like.

**Comment by simon-weber** [comment]
Any luck?
