### ISSUE TITLE
Not synching again

### ISSUE THREAD

**Issue by brianzam** [simon-weber/Autoplaylists-for-Google-Music#202]
Hi Simon,

Synchronisations are failing again.  I'm being careful not to synch too much and it's been fine for months.

Brian

**Comment by simon-weber** [comment]
Hm, I'm not sure I have any new suggestions. My global auth, syncing, and error metrics all look normal, so I'd probably just disable your syncing for a bit to let them recover.

**Comment by brianzam** [comment]
Hi Simon.  No progress - still can't sync.

The Test button doesn't work on an autoplaylist either

**Comment by brianzam** [comment]
Lst sync was 14 days ago

**Comment by simon-weber** [comment]
Ah, if the test button doesn't work then something else is going on. Try [manually reloading](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#reloading-the-extension), and if that doesn't help [send me your background page logs](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs).

**Comment by brianzam** [comment]
Ha, got it!  User error this time - I had an incomplete regex class in a condition and it fell over on any sync or query of that playlist.  As the playlist appears in other playlists, I didn't spot it at first, but inspecting the background page did it.

**Comment by simon-weber** [comment]
Ah, glad you got it figured out. I'd like if those error messages were better surfaced, but it'd require a fair amount of work to hook those parts together.
