### ISSUE TITLE
Google API Chrome Profile bug

### ISSUE THREAD

**Issue by oconshien** [simon-weber/Autoplaylists-for-Google-Music#206]
>Thanks Simon.  That fixed the one problem.  Now I have another.  Even though I’m signed in to Google with the correct user (the one that owns Google Music), when I click the Auto Playlists button, I get:

>Sorry! Due to restrictions in Google's apis, only the user signed into this Chrome profile can use the extension.
#155

> 
> 
> Huh, ok. Well, glad that's working now, and let me know if it happens again!
> 

I just came back to this extension after dropping it in 2017 after the free trial. I subscribed, but cannot use the extension because of this issue. In 2017 I was using a different computer which I no longer have access to, but I'm getting this issue.
[https://i.imgur.com/iPBzQ33.png](url)
![image](https://user-images.githubusercontent.com/9416251/67580692-bf283280-f714-11e9-9a9c-0ab663ec9b9c.png)

I've allowed all permissions. I have tried creating a new profile and deleting all existing profiles, but when I go to sign into GPM using my email which the library is attached to, I just get the same issue.
Will keep the subscription active in the hopes that it corrects itself like this user's experience, but will have to cancel before being charged again.

**Comment by simon-weber** [comment]
I'll respond when I get a chance. No need to send more emails.

**Comment by simon-weber** [comment]
Can you try the debugging instructions from [here](https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/155#issuecomment-305933654)? Note that Chrome seems to clear the protocol of javascript urls these days -- you'll need to manually add the `javascript:` prefix after pasting.

**Comment by oconshien** [comment]
from the console:
`{email: "", id: ""}`

from the javascript popup"`
{"id":" _a 21-digit id, not sure if it's sensitive_ ","email":"oconshien@gmail.com"}`

clearly this is the issue, but I'm not sure how to correct it

**Comment by simon-weber** [comment]
Huh, interesting. Is sync turned on for your Chrome profile? I think that would at least force Google to auth it successfully.

**Comment by oconshien** [comment]
turning Sync seems to have fixed it! I probably forgot to reload the extension when I first tried changing the Sync setting.
thanks

**Comment by simon-weber** [comment]
Great! When I have a chance I'll change that error message to suggest turning on sync.

**Comment by simon-weber** [comment]
Ok, 5.10.8 will have an improved error message.
