### ISSUE TITLE
"Any" in sub-condition isn't working

### ISSUE THREAD

**Issue by johnrobertlawson** [simon-weber/Autoplaylists-for-Google-Music#21]
If I do "Rating = 5" then "Any" of any two conditions, the 'test' is undefined, and the playlist is blank. Doesn't work if the subconditions are "All".

**Comment by simon-weber** [comment]
Huh, this is causing a TypeError deep in lovefield, but I'm not sure why.

**Comment by simon-weber** [comment]
This might be a lovefield bug, so I've opened https://github.com/google/lovefield/issues/118.

**Comment by simon-weber** [comment]
Downgrading to lovefield 2.0.66 fixes this, so I'll do that for now.
