### ISSUE TITLE
Thumbs Up/Down Rating System Issue?

### ISSUE THREAD

**Issue by guapowesley** [simon-weber/Autoplaylists-for-Google-Music#23]
I am having a hard time getting the results I expected when building auto playlists based on rating.  I am using the 0.4.1 beta release.

I see the description: "rating: 0: no thumb, 1: down thumb, 5: up thumb."

My thumbs up playlist has 693 tracks, but building an autoplaylist in your extension yields the following:

Rating equal 5 : 277 tracks
Rating greater than or equal 4: 606 tracks
Rating greater than or equal 3: 776 tracks

Maybe my understanding of the rating system is lacking, or the definition of rating 5 = up thumb is not entirely correct?  Several years ago my music was managed with iTunes, so preexisting ratings could be the issue?

Thank you!

**Comment by simon-weber** [comment]
Huh, sorry for the trouble. Your idea about iTunes rating seems like a good hunch.

How many tracks does "rating greater than 3" yield? If that doesn't match, we can work out a way to diff against Google's playlist.

**Comment by guapowesley** [comment]
Greater than 3 yields 606 tracks (same as "greater than or equal 4")

I found some topics from when Google announced they were eliminating a 5 star rating system in favor or thumbs up/thumbs down and their definition was that previously rated songs would be automatically converted using the following: 1-2 stars = thumbs down, 4-5 stars = thumbs up.  It was not stated, but I assume that 3 stars = no thumb

I will continue to manipulate settings and let you know if I find something insightful.

**Comment by guapowesley** [comment]
Well, I realized the difference and it is actually quite simple.

The Thumbs Up auto playlist (created automatically by Google Play) will include songs that are not actually in my library (ie. songs that I have given a "thumbs up" while using the streaming service).  Therefore, there are 693 - 606 = 87 such songs.

I suppose it is beyond the scope of your extension to be able to include those songs.

**Comment by simon-weber** [comment]
Nice find; I had no idea it did that. Yeah, I don't see an easy way to get those tracks into a playlist, sorry =(

Somewhat related, I remember gmusicapi having trouble even getting the rating for those tracks: https://github.com/simon-weber/gmusicapi/issues/182.

**Comment by simon-weber** [comment]
I'm going to close this for now. I may add a note about this discrepancy to the explanations section (I'm looking to overhaul that ux eventually).
