### ISSUE TITLE
Show real number of matching songs during test

### ISSUE THREAD

**Issue by sschuberth** [simon-weber/Autoplaylists-for-Google-Music#25]
Even though playlists are limited to 1000 songs, is there a way you could show the real number of matches when testing a playlist definition? I.e. in `Matched X tracks. The first was ...` the `X` should be able to exceed 1000.

**Comment by simon-weber** [comment]
Ah, good idea. This should be pretty straightforward to do.

**Comment by simon-weber** [comment]
Thanks for the suggestion! You should see the update in the web store shortly.

**Comment by sschuberth** [comment]
Working great, thanks!
