### ISSUE TITLE
figure out how to let people pay

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/Autoplaylists-for-Google-Music#26]
I've gotten questions from a few folks about donations, so I guess it's time to figure that out.

Here's my most recent plan, copied from an older comment on an unrelated issue:
* free version: all features, but limited to one playlist
* full version: no limit on playlists. $2 a month? I'd love to do $1+ pay-what-you-want, but the Web Store doesn't have an easy way of doing that.
* keep everything open source. contributors get full tier for free (by adding their email to be a trusted tester, which I need to check doesn't violate some ToS).
* people can build from source and sideload if they really don't feel like paying

Feedback in the issue would be great, but I'm also planning to link it where people ask me about it (so feel free to reply there instead).

**Comment by johnrobertlawson** [comment]
I think a limited free version plus paid-for full version. There are a few of us playlist nerds very willing to pay ($3-5?) but many for whom it's maybe not attractive to pay for.

**Comment by simon-weber** [comment]
> the need for ongoing development with Google changing the code...

Yeah, that's the main thing pushing me towards a subscription: I'm all too familiar with unofficial clients breaking through my work on https://github.com/simon-weber/gmusicapi. 

What I really like about the subscription is the option to stop taking payments immediately if eg I can't keep up with their changes, or Google decides to shut us down, or someone takes advantage of the license, etc.

**Comment by PeteRepeat77** [comment]
I used to use a chrome extension that was for grouped no tans together and that you could pay for certain amount of groups of tabs. So the more you utilised the app, the more you paid. 

I'd suggest something like this. 2 dollars a month is not a lot of money,  but when compared to the subscription only being 10 usd a month it does seem a little high..

Although I do respect the large effort you have put in, the amount of improvements you've made in such a short time,  and how promptly you have resolved problems so I would pay that if it continually gets developed, especially with a small user base at the moment where you deserve a decent reward for your work.

**Comment by simon-weber** [comment]
> So the more you utilized the app, the more you paid. [...] I'd suggest something like this.

I've considered something like charging per playlist "slot", and giving the first one away for free. On one hand, I like how that's closer to value pricing (with the assumption that more playlists -> more value). On the other, I don't really like the way it aligns incentives: it makes users want to use it _less_ - "hm, maybe I don't need that extra playlist" - and feels a bit like nickel-and-diming to me.

> ...when compared to the subscription only being 10...

An excellent point. That's a tough sell: does this give ~20% of the value of Google Music? I think in my case it does - it's the only way I listen to my library anymore - but I was also so into the idea that I built an extension, haha.

Ideally, I'd prefer that paying be looked at similarly to being a patreon supporter or twitch sub: it's not me looking to cash in on my work, but rather people allowing me to do more things like it in the future. Unfortunately, those setups don't seem to work well with small user bases, and I'd really like to get some experience on the business side of selling my own software (eg figuring out with the legal and tax implications).

**Comment by simon-weber** [comment]
Alright, here's what I'm planning to try to start with:
* one copy of the extension on the web store
* free version works indefinitely and allows syncing one playlist
* paid version is charged per month and allows syncing as many playlists as desired
* paid version is Google's lowest payment tier: $1.99, or €1.49. See [this link](https://developer.chrome.com/webstore/pricing#matrix) for amounts in other currencies.
* contributors can use the full version for free, controlled by a whitelist of google ids in code that I maintain.

Here's how transitioning between states would work:
* beta/paid -> free: all but the first playlist are "locked". The last version of locked playlists will be available on Google Music, but will no longer sync. Locked playlists' rules will not be deleted, but will no longer be editable. Users can choose to delete them if they'd like. The "Add an autoplaylist" button will also be locked. Tooltips will be used to explain these states on hover. This transition will be detected automatically at the granularity of around a day.
* free -> paid: locked playlists will begin syncing. Locked buttons and links will become functional. Users click a "I bought the full version" button to trigger this transition, since we need to trigger an interactive OAuth flow that can't be done in the background.

Here's a draft of hovering the "locked" ui elements:
<img width="673" alt="screenshot 2016-01-31 11 04 33" src="https://cloud.githubusercontent.com/assets/950506/12703187/dc7fbd86-c80a-11e5-8479-b18d2a72c8af.png">
<img width="631" alt="screenshot 2016-01-31 11 04 43" src="https://cloud.githubusercontent.com/assets/950506/12703188/dee60ab2-c80a-11e5-8c44-103a6b59c945.png">

**Comment by simon-weber** [comment]
Oh, and here's how I plan to roll this out:
* this month: ui for locked states goes out. "Contributor" access checks will return true for everyone, allowing them to toggle between free and paid states using a button in the extension. This will let people test out transitions, while still allowing full access prior to being available for purchase.
* march 1st: contributor access checks are turned on, and the extension will be available for purchase to people on the mailing list. This will let people test the free -> paid transition for real.
* mid-march: the extension is opened to people outside the mailing list.
