### ISSUE TITLE
support random sorting

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/Autoplaylists-for-Google-Music#33]
Sourced from [this mailing list post](https://groups.google.com/d/msg/autoplaylists-for-google-music/X6s9gQQcPxw/13XLcHHUCwAJ).

It seems like they're looking for this option as a workaround for the 1k playlist limit, which is something that's been mentioned before (though I think in the context of "include random songs until the playlist reaches 1k).

I'm not sure how exactly the ux for this should work, since the simplest (stateless) implementation would shuffle the list every minute.

**Comment by simon-weber** [comment]
If the goal is working around the playlist limit, https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/39 addresses it more directly.

A random story could still be useful for "filling in" the rest of a sub-1k playlist, though.

**Comment by johnrobertlawson** [comment]
Hi Simon,

I've been interested in this for a while for the same reason as in #39 (I have "not heard in XX days; thumbs up" style playlists). Are you thinking of a genuine randomness built into a codebase (Lovefield right?), or something like a randomness seed or logic based on the time of day the playlist is generated (e.g. pick track IDs that are a multiple of x, then y, .... until playlist limit is reached)?

**Comment by simon-weber** [comment]
I haven't thought about this in a bit. How do you imagine it working? What problems are you looking to solve with it?

**Comment by simon-weber** [comment]
[This post](https://groups.google.com/d/msg/autoplaylists-for-google-music/gt_GlALdVqo/pnbJo3ObBQAJ) suggests setting the seed whenever the Music tab is refreshed, which is straightforward and seems like reasonable UX.

**Comment by simon-weber** [comment]
I could see this helping a lot with https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/39 now that static playlists can be linked: it'd let you create a random 1k subset of your 1k+ playlist (that's been split across multiple lists).

**Comment by simon-weber** [comment]
I thought up a clever way to implement this: just assign each track a random number on load, then sort on it like other fields. This gives a lot more flexibility than just adding a "shuffle the result" option, since you can sort on multiple fields. For example, sorting on (album, random) yields one album with its tracks shuffled, then the next...

As a bonus, this way is super easy to implement. The only downside is that it might be confusing without knowing how it works under the hood. We'll see.

**Comment by simon-weber** [comment]
I offloaded the explanation to the wiki. I'm particularly excited about my new pomodoro playlist! https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Tips-and-Tricks
