### ISSUE TITLE
support working around 1k playlist limit

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/Autoplaylists-for-Google-Music#39]
**edit**: this is handled pretty well today; see [the wiki](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Tips-and-Tricks#combined-with-a-limit) for details.

- - -
Sourced from [this mailing list post](https://groups.google.com/d/msg/autoplaylists-for-google-music/ETTUJJFUK9I/dknbqM75DQAJ):
> I have some playlist rules matching more than 1k results, and due to Google limitation on number of tracks in a playlist, I am locked with only 1k tracks in a playlist relatively to sort criteria.
As an alternative, is it possible to add extra fields to the limit option in order to :
- choose from $number to $number in result (choose from 1001 to 2000 to create an extra playlist for example)
AND/OR
- check an option to automatically create multiple playlists for each set of 1000 tracks (playlist1 (1 to 1000), playlist2 (1001 to 2000), playlist3 (2001 to last) for rules matching more than 2k tracks for example)

The first could be done by exposing lovefield's `skip`. The second would be a bit trickier, since it'd require some new syncing logic (creating/deleting playlists based on number of tracks).

**Comment by yokaiichi** [comment]
This feature is highly desirable. Many of my preferred playlists end up being larger than 1000 results, so I often have to limit my preferred conditions to cut down the result set < 1000.

**Comment by simon-weber** [comment]
@yokaiichi thoughts on the first solution (exposing a param for number of results to skip)? It'd be very quick to implement and could be useful for other situations, but would require you to do a bit of work for each playlist you want to extend. We could make it a little bit easier by adding a way to copy an existing playlist (so you just copy, then edit name and skip value).

**Comment by yokaiichi** [comment]
I think it's fairly simple to look at test results that show 1733 songs and say "Hmm, let me specify "Skip 0" for the first instance of this playlist. Then I'll create a second playlist and specify "Skip 1000". I think that's intuitive enough, but you might want to summarize that "trick" in the notes at the bottom of the **Playlist Definition** UI.

A copy playlist function would indeed help this UX workflow quite a bit. :)

**Comment by yokaiichi** [comment]
Hmm, I wonder about one particular use case though.  What happens when a "split" playlist like this uses a "lastplayed" condition?

- First playlist is songs 0-1000
- Second playlist is songs 1001-1733

Now I listen to the first playlist for a while and 33 songs are no longer meeting the condition for playlist 1, so in the background, as I've been listening, the extension has been removing those 33 songs...

...But the conditions are also trying to _refill_ the playlist back up to 1000 songs!

- Do the 33 new songs essentially get duplicated from the 773 that were originally in the 2nd playlist?

Does this description make sense? I would imagine that users would end up with duplicates among their "split instances" this way, and I would imagine that the logic to prevent this from happening would be really difficult.

**Comment by simon-weber** [comment]
I'd need to play around with it to be sure, but I'm not super worried about it. Since both of the playlists have the same query, it should work as if the two were split from one pre-existing bigger playlist, which should prevent duplicates. Tracks should seamlessly be moved across the split "border" during syncs.

I can think of two things likely to mess this up, but neither seem particularly bad:
* because the split playlists update at different times, it's possible that the query returns different results for each. In the case of last played, this should only be off by one song, but for other fields you could potentially get unlucky with a batch mutation and be off by more. It should be fixed in the next sync (so long as you don't hit the race condition again). I'm not sure there's an easy way around this: we'd need the db to know that the playlists should share a query result, and at that point we may as well do the first-class solution.
* there's a special bit of logic that [prevents currently-playing songs from being removed from playlists](https://github.com/simon-weber/Autoplaylists-for-Google-Music/blob/8182e3dd630dda876249e2930b602b643719001d/src/js/googlemusic.js#L304). This would push track index 999 out of the playlist (since the currently-playlist track takes an extra spot compared to the local query results), and since the next split playlist doesn't know this happened, it wouldn't shift back its results to match. Again, it's not impossible to fix, but the currently-playing fix is already a hack, and I don't want to pile things on top of it :grin:

**Comment by simon-weber** [comment]
Heads up that linking non-autoplaylists is now supported, meaning you can chop up your big playlist into chunks, then combine then in some special way with an autoplaylist. While this doesn't directly solve the problem, it's a useful tool for working around it.

Check out the announcement post for more details: https://groups.google.com/forum/#!topic/autoplaylists-for-google-music-announcements/IO_7xKUFW0Q.

**Comment by simon-weber** [comment]
Random sorting is now also supported. Putting these together results in [a pretty good workaround for the 1k track limit](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Tips-and-Tricks#combined-with-a-limit).

Since this issue is getting a bit long, I'm going to close it and open a new one for exposing skip (which I think is still worthwhile).
