### ISSUE TITLE
improve UX around 1k+ playlists

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/Autoplaylists-for-Google-Music#5]
Google doesn't support playlists over 1000 tracks [0]. We handle this by automatically truncating and logging a warning, but this should definitely surface in the ui.

[0] https://support.google.com/googleplay/answer/1250213?hl=en

**Comment by PeteRepeat77** [comment]
Just an idea.

 In my case I plan on having unrated and thumbs up in a play list.

Could the generated playlist include all unrated (assume under 1k), then fill the remainder of the 1k tracks filled  with random thumbs up, or the choice of latest thumbs up instead of random? 

Other idea is to split the playlist in multiple playlists of 1k. With the playlist having an extension of say "_1" etc added at the end. That  way one can be added in play music to the queue,  and then manually add the other split playlists to the queue.

**Comment by simon-weber** [comment]
> Could the generated playlist include all unrated (assume under 1k), then fill the remainder of the 1k tracks filled with random thumbs up

I think you could make this playlist with the current definition language once sort/limit support (https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/9) is added. It'd look something like:
* any:
  * rating == 0
  * rating == 5
* sort by rating asc
* limit 1000

I don't think "latest thumbs up" would be possible, though, since Google only records the last track modification of any type.

> one can be added in play music to the queue, and then manually add the other split playlists to the queue.

Clever. Does the queue support more than 1k tracks at a time?

**Comment by PeteRepeat77** [comment]
All sounds great regards sort and limit answer. Looking great for my needs. 


I'll try the 1k queue limit shortly. You have a good point there

**Comment by PeteRepeat77** [comment]
Looks like the queue is also limited to 1k songs damn.

**Comment by simon-weber** [comment]
Let's see if always showing the limit and linking Google's docs feels like enough to solve this.

**Comment by PeteRepeat77** [comment]
I know this is closed but I might look into adding a "not played" in the last month or "played" in the last 20 minutes to the criteria to keep the list changing rather than always the same 1k songs.

**Comment by simon-weber** [comment]
> to keep the list changing rather than always the same 1k songs.

I've thought adding "shuffle" as an option so you could randomly select those under the order, but that would cause refreshing on every sync. If it's something people want, though, we could look into it.
