### ISSUE TITLE
PSA: If you ever tried the "Ratings" feature from Google Labs, you must use all possible rating numbers

### ISSUE THREAD

**Issue by yokaiichi** [simon-weber/Autoplaylists-for-Google-Music#54]
I couldn't edit the Wiki or FAQ directly, so dropping this here.  Once upon a time, Google Labs for GPM tested out a 5-star rating system like iTunes uses. About 6 months ago (maybe longer), they yanked that feature and went back to Thumbs up/down/none for rating.

At that time, any existing rating of:
- 1-2 became "thumbs down"
- 3 became "no thumb"
- 4-5 became "thumbs up"

So after some testing, it's apparent that this extension will not find all current "thumbs up" songs if you use _only_ "Rating EQUALS 5". To find all current "thumbs up" songs, you _must_ instead specify an ANY subcondtion that looks for both "Rating EQUALS 4" and "Rating EQUALS 5".

Likewise, to find all current songs that have "no thumb", you _must_ specify an ANY subcondition that looks for both "Rating EQUALS 0" and "Rating EQUALS 3".

Hope this helps others who think they're running into bad results with any auto-playlist that includes ratings (sub)conditions.

**Simon:** Perhaps the notes at the bottom of the Playlist definition UI could be changed slightly to mention that "If you ever used the old 5-star ratings lab, your songs are still internally tagged with values 1-5 and you must create conditions accordingly".

**Comment by simon-weber** [comment]
Ah, yes. I actually got this feedback a while ago (https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/37), but apparently made a poor copy choice :grin:

Sorry for the trouble, and thanks for bringing it up! It looks like we can ease the common case of "thumbs up" a bit by suggesting "rating greater than 3". Too bad thumbs down and none won't work without a subcondition; they're kind of unwieldy.

I'm also wondering if it'd be good to just make an artificial field like "thumb rating" with a dropdown like "up", "down", and "none", since that matches what users see in the current GPM ui.

**Comment by simon-weber** [comment]
Oh, we actually could make that work, but it'd be a breaking change: I think the 0 values are predominantly nulls that have been coerced from https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/15.

**Comment by yokaiichi** [comment]
I like your idea of a drop-down with three values (thumbs down, no thumb, thumbs up). That way, users don't have to remember or know about the old Google Labs thing. It matches what they see in the GPM UI today.

Your internal logic for the three drop-down choices can handle all the internal mapping to old 5-star values (and to null/0).

**Comment by simon-weber** [comment]
I went with a quick fix for now: a non-dropdown with explanation, while leaving the existing rating field around.

We can clean up the ui in the future; it was more than I wanted to think about this late :sweat_smile:

**Comment by yokaiichi** [comment]
Tested all my existing playlists by converting to the new "thumbs up" filters. Used before and after tests to ensure the song count was the same, and also checked download manager on my iPhone to ensure that no new downloads occurred when changing the filters. All work as expected. Thanks!

**Comment by simon-weber** [comment]
Glad to hear it! Thanks for testing it out.
