### ISSUE TITLE
Thumbs Down included even though excluded from the cirteria

### ISSUE THREAD

**Issue by PeteRepeat77** [simon-weber/Autoplaylists-for-Google-Music#57]
For some reason I am getting thumbs down songs in the playlist attached.

Either songs changed to thumbs down stay in the playlist, but already existing thumbs down are also included.... Strange I know. Any thoughts?
![image](https://cloud.githubusercontent.com/assets/15964601/14399170/707eca60-fe2d-11e5-95f5-6d02bdf98b28.png)

**Comment by PeteRepeat77** [comment]
It's meant to included Thumbs Up and no rating (added to library only) and all songs shouldn't have been played recently.

**Comment by simon-weber** [comment]
Ah, that's because the outermost "Any" applies to the "All" down below, so any track with a last played before 30 days ago is included, regardless of rating thumb.

If I'm understanding what you want correctly, this will select all not-recently played tracks that have an up or none thumb:
```
all(
  last played before 30 days ago
  rating thumb does not equal down
)

**Comment by PeteRepeat77** [comment]
Ahh OK.

So my old playlist was this affectively was it?

If "Thumbs Up" OR "thumbs down" OR "not played recently"

Rather than;

If "Thumbs Up" OR "thumbs down"

**Comment by PeteRepeat77** [comment]
On another note (rather than open a topic) I'm assuming my playlist wasn't updating because it had NaN in the sync period field? Is there a push value or does it need to be entered as an integer in minutes? I've changed mine to 60 minutes as I don't need the playlist updated dynamically really

**Comment by simon-weber** [comment]
> So my old playlist was effectively this was it?

Yup. The query always has a root boolean operator that everything else is nested under.

> On another note (rather than open a topic)

Let's track this separately. It sounds like a bug.

**Comment by PeteRepeat77** [comment]
This playlist seems to include any tracks I recently rated as thumbs down for a while. Even after multiple syncs.

Got up this morning and they were removed however.

Is this because there is a buffer of time to remove any recently played tracks so they don't get removed from playlists while still playing the tracks?

**Comment by simon-weber** [comment]
The delay should only be as long as the length of the track, so it's probably not that.

Were you rating from the same computer you were syncing from? If you were instead rating from a mobile device, I know that those requests get batched up and sent to the server later. Otherwise, I'm not sure what happened. It could just be that Google delays sending rating changes over the differential update endpoint.

**Comment by PeteRepeat77** [comment]
Yes rated from an android phone but I noticed there were thumbs down in a playlist with condition thumbs rating  "does not equal" "down" on the pc I created the auto  playlist from. 

I'll report again if I see this behaviour.

**Comment by PeteRepeat77** [comment]
I'll start a new topic if I can repeat it
