### ISSUE TITLE
playlist descriptions should use the same operation labels as the ui

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/Autoplaylists-for-Google-Music#59]
Currently, a playlist description might look like:
```
(lastPlayed < 60 days ago and playCount > 11) sort by playCount descending
```

It'd be better if it looked like:
```
(last played earlier than 60 days ago and play count greater than 11) sort by play count descending
```

**Comment by Yinka** [comment]
Will it also be possible to display date as May 01, 2016, instead of 05/01/2016 - I get confused all the time with the US date format.

Thanks

**Comment by simon-weber** [comment]
Oh, actually, I think it should already be outputting the date according to your browser's locale. Can you see if that's set to what you expect?

**Comment by Yinka** [comment]
Yep, thanks

**Comment by simon-weber** [comment]
Sure thing.

**Comment by Yinka** [comment]
Looks like the US date format is back: 

![image](https://cloud.githubusercontent.com/assets/87303/15199409/dfbe66b2-17d5-11e6-9daa-38f21c0ec1ec.png)

Not sure if this needs a separate ticket but looks like sync is broken, hasn't synced for about a day - last sync was 10/05/16, its now 12/05/16. `Test` returns the below:

![image](https://cloud.githubusercontent.com/assets/87303/15199650/14147472-17d8-11e6-8d28-581fec869225.png)

Thanks

**Comment by simon-weber** [comment]
Can you check the logs to see if anything stands out? If everything looks ok, try disabling and re-enabling the extension, then refreshing the Music tab. If that doesn't work, let's track it in a new ticket.

**Comment by Yinka** [comment]
I did the disabling/re-enabling thingy a couple of times last night which didn't help so I logged the issue here

However, waking up this morning, sync is back without me having to do anything. Strange.

Thanks.

**Comment by simon-weber** [comment]
Weird. Glad it's working again.

If it happens again, try to [save your logs](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs) so I can take a look.
