### ISSUE TITLE
NaN for sync period

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/Autoplaylists-for-Google-Music#60]
From #57, @PeteRepeat77 said:

>  I'm assuming my playlist wasn't updating because it had NaN in the sync period field? Is there a push value or does it need to be entered as an integer in minutes? I've changed mine to 60 minutes as I don't need the playlist updated dynamically really

I'm not sure how that happened. It's supposed to default to 1 minute. Was is set to NaN the first time you opened the settings page?

**Comment by PeteRepeat77** [comment]
Yes. I don't remember changing the sync setting ever. Pretty sure the extension is updated to the latest store  version but can check when at home.

**Comment by simon-weber** [comment]
Huh, sorry about that. Something must have gone wrong adding the new setting.

**Comment by PeteRepeat77** [comment]
No problem. I wondered why the thumbs down songs (recently changed rating) were still in the playlist... Was because the playlist hadn't updated since I changed the conditions.

**Comment by simon-weber** [comment]
I'm going to be completely honest: I have no idea how that happened, haha. This ought to fix it, though.

**Comment by simon-weber** [comment]
Oh, and thanks for letting me know! I noticed a drop in syncs in GA, but I didn't think much of it since people tend to use the extension less on weekends.
