### ISSUE TITLE
removing vs retaining tracks in playlists

### ISSUE THREAD

**Issue by DaveChild** [simon-weber/Autoplaylists-for-Google-Music#61]
If I set up a playlist with these criteria:

     (genre = Podcast and rating ≠ 1 and playCount = 0) 

Once the playCount reaches 1 will the item be removed from the list automatically? It doesn't seem to, in the case of the one above.

Actually, regardless of how it works at the moment, it would be nice to be able to set that as a per-playlist option. So, for that playlist, I'd prefer to remove items automatically after listening to them, as I often listen to a single podcast over, for example, two or three car rides, giving a play count of three before I finish listening. But for another playlist (tracks with a year > 1990 and year < 1999) I would want to remove items that didn't match any more.

**Comment by simon-weber** [comment]
Yup, this should remove tracks from the list on the next sync if they fail to match the query (though in the very specific case of checking for playCount == 0, there's a Google bug we're currently trying to work around: https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/55). When playcount is incremented also [seemingly depends on your client](https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/18#issuecomment-164203689).

>  it would be nice to be able to set that as a per-playlist option

That's really interesting, and not something I had considered before. Unless there's a typo, though, those two examples are in favor of removing tracks? I'm having trouble thinking of an example playlist where retaining tracks would be useful.

If it's something people find useful enough to justify the ui/ux complexity, it wouldn't be that hard to implement.

**Comment by DaveChild** [comment]
The first example is in favour of not removing tracks. I sometimes listen to podcasts over two or three sessions (if they're over an hour, usually). Every time I listen, even to part of the track, the play count goes up by 1. I want the "playcount=0" so I can add new, unheard podcasts to the playlist, and won't accidentally re-add the ones I've already listened to. But I don't necessarily want to immediately remove one with a playcount of 1, because I might have only listened to half the track. 

I tried a playlist with a "last played" filter, so if a track was last played within the last week, it would also be added to this playlist. 

The problem is, I sync this playlist to my phone, and have limited space. So, it's limited to 20 tracks. I either have to have 20 completely fresh podcast tracks, and remember in meat-space what tracks I've half-heard, or include tracks I've listened to in the last week and end up with a playlist that's mostly stuff I've already heard and don't want to listen to again.

If there was a quick way to flag something as "don't include in this playlist", that would be ideal. I'm using the thumbs-down icon that way at the moment, but that means I can't mark something I liked with a thumbs-up.

**Comment by simon-weber** [comment]
Sorry, my bad; I misunderstood that.

> Every time I listen, even to part of the track, the play count goes up by 1

Bleh, this is so annoying. How Google does this seems to vary between clients and tiers. The last time I checked {web, free} only incremented after the entire track was played, but {web, paid} incremented after the first 10 seconds or so. I haven't checked what the mobile clients do. I'd suggest reporting it to Google, and maybe they'll eventually do something about it. I can't imagine it's intended.

> If there was a quick way to flag something as "don't include in this playlist", that would be ideal

Hm. There's always the comment field for arbitrary data, but I'm not sure it's possible to edit it from the mobile client (and even if it was, it'd probably be a pain).

You could potentially rate all the podcast tracks you've listened to, then filter on `rating thumb is none`? That at least lets you use up or down ratings.

Or, depending on how you add podcasts to be listened to, you could do something like "date added to library between now and one week ago" to make sure it's always the recent ones, plus something like "added in the past month and is unrated" to get any of the ones you've flagged.

**Comment by PeteRepeat77** [comment]
I was going to suggest thumbs rating.

Unrated (remove thumb) or never rated are the ones you want to still listen to. 

Thumbs up means you're done with it but liked it and thumbs down is listened and don't like it.

**Comment by PeteRepeat77** [comment]
So the playlist will include only the podcasts with thumb rating "none".

**Comment by simon-weber** [comment]
I think this is resolved with the suggestions, but feel free to reopen if there's something more to be done.
