### ISSUE TITLE
Chrome Music Library Refresh Issue

### ISSUE THREAD

**Issue by Yinka** [simon-weber/Autoplaylists-for-Google-Music#64]
I've noticed for about 2 weeks now that Chrome (v50) is refusing to load load all my music library, loads only about 7,000 songs instead of the **13,000** songs I have uploaded. (I don't have All-Access)

![image](https://cloud.githubusercontent.com/assets/87303/14792160/fa048c3a-0b10-11e6-8d6f-95e3432f0482.png)

Clicking the REFRESH LIBRARY button in Settings doesn't help, in fact it makes it worse, each time I click that button, songs available in my library decreases further (funny thing is, it decreases by exactly 1,000 songs)

![image](https://cloud.githubusercontent.com/assets/87303/14792342/b5abb530-0b11-11e6-9cab-d718e01369bf.png)

 
What this means is that my auto-playlists are always wrong, missing songs and constantly changing. 

 - Is this issue caused by this extension in any way? (probably not, but I've only noticed it since I started using the extension so I may as well ask) 
 - is anyone else here experiencing the same issue?
 - Is there a workaround / a way to force the full library to load

Thanks in anticipation

**Comment by simon-weber** [comment]
Huh, that's pretty odd. I haven't heard of anyone else having issues like that. https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/53#issuecomment-205969688 is the most similar problem, where the extension was presumably putting too much load on Google's servers.

Things you can try:
* go to chrome://extensions and uncheck the enabled button, then wait a bit and see if it gets any better
* if that works, try re-enabling and increasing the sync interval until you don't see problems anymore

**Comment by Yinka** [comment]
I already disabled the extension this morning GMT + syncing interval was set 30 minutes anyway so I doubt if its that.  

Anyway, I'll keep it disable until tomorrow and then see whats up in the AM

And I've already reported this to Google too.

**Comment by simon-weber** [comment]
Sounds good; let me know how it goes.

**Comment by Yinka** [comment]
I still have same issue in Chrome, I'll chase Google for answers.

I now use [GPMDP](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-) for desktop playback as it shows my entire library unlike Chrome.

**_gpmdp:_**
![image](https://cloud.githubusercontent.com/assets/87303/14816406/a21eb8fe-0ba8-11e6-8518-8a70d8d1b86f.png)

**_chrome:_**
![image](https://cloud.githubusercontent.com/assets/87303/14816431/c1fe542c-0ba8-11e6-89ce-f9dd049b7005.png)


Is there a way for your app to work with GPMDP? (maybe in the future if not now)

![image](https://cloud.githubusercontent.com/assets/87303/14816080/db522a0e-0ba6-11e6-909f-75776d695301.png)

Cheers

**Comment by simon-weber** [comment]
Here's another idea: follow the instructions [here](http://stackoverflow.com/questions/9384128/how-to-delete-indexeddb-in-chrome) to remove the local indexeddbs for play music and force them to repopulate. There's evidence of indexeddbs getting out of sync for other users (https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/55#issuecomment-208937051).

> Is there a way for your app to work with GPMDP?

I don't think so; since it's an extension, it's pretty heavily tied to Chrome.

**Comment by Yinka** [comment]
Clearing indexeddb hasn't solved the issue, is it possible that indexeddb is permanently out of sync?

I'd find time to try one more thing - remove and reinstall all chromes (1 at work + 2 at home)

**Comment by simon-weber** [comment]
Hm, that's not possible in my understanding at least: if it's not present, Google's client will retrieve your entire library from the server instead. 

It sounds like the problem is on their backend? One more thing you can try to rule out client state: try visiting the site from an incognito tab.

**Comment by Yinka** [comment]
> One more thing you can try to rule out client state: try visiting the site from an incognito tab.`

I tried already, no joy. 

The first time I tried incognito, library was correctly loaded, however this stopped on second and subsequent launches. Also it seems your extension wont sync from the incognito tab anyway, while `Allow in Incognito` shows the icon on the incognito tab, clicking on the extension icon opens it in a separate normal tab and not the incognito tab.

**Comment by simon-weber** [comment]
Got it. I ticketed that separately.

**Comment by Yinka** [comment]
Removing chrome in its entirety (not just indexdb) seem to have solved this,  I hope its permanent.

**Comment by simon-weber** [comment]
Huh, no idea what happened, haha. Glad you got it fixed though.
