### ISSUE TITLE
Leading/trailing spaces

### ISSUE THREAD

**Issue by Yinka** [simon-weber/Autoplaylists-for-Google-Music#68]
Will it be possible to ignore trailing/leading spaces in metadata if they are the same word and case, e.g. at the moment, if you define _Genre = Rock_, ` Rock` or `Rock ` with a leading or trailing space will not be returned.

It's hard to notice these trailing/leading spaces in your metadata because Google ignores them i.e. Google music groups genres written as `Rock`, ` Rock` or `Rock ` as one while AutoPlaylists' `equal` does not, I think Autoplaylist should also ignore them like Google does.

Just to also note that Google Music takes it further by grouping `Afro-Rock` and `Afro Rock` together and ignores the hyphen though this is not an issue in Autoplaylist.

**Comment by simon-weber** [comment]
Sounds reasonable to me.

**Comment by simon-weber** [comment]
I plan to release this later tonight. Thanks for the idea!
