### ISSUE TITLE
optimize sync api calls

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/Autoplaylists-for-Google-Music#73]
Right now, a single sync cycle looks like:
- **diff update library call**
- for each playlist
  - **edit description call**
- for each playlist, retry the following until it matches
  - set contents
    - **load playlist call**
    - if needed, **add tracks call**
    - if needed, **remove tracks call**
  - set order
    - **load playlist call**
    - if needed, **reorder tracks call**

There are a few potential improvements here:
- pull up the load playlist call to avoid the second call. We'd need to manually build the modified playlist using the add/remove responses if we go this route, which might be tricky.
- move the description edit after the retry block and only edit when needed. I'm not sure this is a good ux decision, since we'd need to move the timestamp out of the description to ever avoid requests this way.

I used to think we could make a big difference by also pulling out the load playlist call and making 1 call per operation, rather than 1 per playlist. But, it doesn't look like the api supports that: their client makes n calls when getting contents, and the update calls all receive a single playlist id as a param. Bummer.

**Comment by Yinka** [comment]
Does you last edit mean that no optimization is possible here? 

Thanks.

**Comment by simon-weber** [comment]
Pretty much. At least, I don't see anything straightforward.

The ideal optimization would be a way to batch together operations (across playlists or for a single playlist). Their [mobile apis support this](https://github.com/simon-weber/gmusicapi/blob/44fd2cce848dbcdb2ca4ab2111b9a0441aacc2dc/gmusicapi/protocol/mobileclient.py#L599), but I've never found an equivalent in their web api.

There is one related bit that I've never been able to figure out: their client manages to apply large updates immediately, while mine usually takes a few retries when done with the same params. I suspect this has to do with a complicated-looking cache invalidation request that their client makes. If we were able to figure out how to replicate that, we could potentially save on retries (which currently make up about half of all sync attempts).

The main benefits of improvements like these would be less ui refreshes, faster convergence, and possibly more accurate syncing.

**Comment by simon-weber** [comment]
See https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/97#issuecomment-261741997; I'm planning a switch to the mobile api mentioned above that will include these changes.
