### ISSUE TITLE
Extension Won't Load Anymore

### ISSUE THREAD

**Issue by DaveChild** [simon-weber/Autoplaylists-for-Google-Music#74]
Used to work fine for me, but now the icon doesn't show in the address bar any more. There's an error in the Chrome console as well:

    Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode - content.js:3308

The line is:

    let userId;

**Comment by DaveChild** [comment]
This is Version 47.0.2526.106 (64-bit) on Ubuntu, if that makes a difference.

**Comment by simon-weber** [comment]
Huh, sorry about that. I'll add back the strict mode declarations. I removed them because eslint complained and it worked when I tested in my chrome, haha.

**Comment by simon-weber** [comment]
Ah, yeah, it looks like that's 49 specific according to http://blog.chromium.org/2016/02/chrome-49-beta-css-custom-properties.html:

> Improved ECMAScript 2015 support
The ES2015 specification (ES6) is a major update to JavaScript that allows developers to write application logic that is more legible, powerful, and memory efficient. [...] *The latest version of Chrome also makes block-level constructs such as class and let available outside of strict mode.*

Looks like it might be time for me to have some basic automated tests across different version of chrome, huh?

**Comment by simon-weber** [comment]
Ok, 1.5.2 is up with the fix. Sorry again, and thanks for letting me know!

**Comment by DaveChild** [comment]
Thanks, all working again now.
