### ISSUE TITLE
Google-provided lastPlayed seems incorrect

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/Autoplaylists-for-Google-Music#8]
I double checked that I'm using the correct field, but `lastPlayed` still doesn't make any sense. I'm seeing tracks that I haven't played recently (or ocasionally ever) with recent playtimes that aren't correct. Most of time it seems to be roughly correct, though.

`albumPlaybackTimestamp` and `recentTimestamp` are worth looking at too.

**Comment by johnrobertlawson** [comment]
This field is a problem via e.g. Gear Player for Mac. Some of the tracks have the field filled; others don't. Mystery!

**Comment by Yinka** [comment]
Hi Simon, is this a google-bug issue now fixed?, i.e lastPlayed.

I noticed yesterday that tracks I've played recently on my iPhone were showing as not haven't been played in the last 15 days.

**Comment by simon-weber** [comment]
Nope, I haven't noticed any changes here. If the data's wrong and we can't get it from another field, there's not much we can do.

If you have a way to reproduce lastPlayed not being written, it'd be good to let Google support know.

**Comment by Yinka** [comment]
Can we still report this even though there's no official api? :)

Y

**Comment by simon-weber** [comment]
Yup, I don't think it'd hurt. If they wanted to shut the project down, I suspect they already would have 😁 

There's also a similar thread in another issue: https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/55#issuecomment-208380170.

**Comment by simon-weber** [comment]
We may have just cracked this on the mailing list: https://groups.google.com/d/msg/autoplaylists-for-google-music/EtcYNBbCdfM/DDLiOPu-AwAJ.

**Comment by simon-weber** [comment]
I'm pretty confident in this new field. It's not perfect - there are still some false positives where the field is 0 but the playcount is >0 - but it does seem accurate for values after 4/24/2013. I wonder if Google realized the old field was messed up and switched to this field around that date?
