### ISSUE TITLE
Request: Ability to add comment to all songs in a playlist

### ISSUE THREAD

**Issue by rcmpayne** [simon-weber/Autoplaylists-for-Google-Music#85]
Not sure if this is out of your ability but it would be cool if i could select a playlist from my collection (could be one that i created with your app or another one that was created via Google Music) and upload a comment to every song within. this way, i can upload something like "Created 8.8.2016". from here and over time, i can rebuild playlist using the comments condition.

I'd gladly donate a sum for this feature.

**Comment by simon-weber** [comment]
I think you can actually do this through Google's interface! Assuming you have the "track comments" lab enabled, you can:
* create a playlist, either through Google or through an autoplaylist
* open it in the web interface
* click the first track to select it
* scroll to the last track, hold shift, and click it to select all tracks
* right click -> edit info -> edit comment field

Then if you want, you can select on the comment inside autoplaylists later on.

**Comment by rcmpayne** [comment]
odd, i have the lab enabled and i cant do this for one song or multiple. Using Chrome RTM

**Comment by simon-weber** [comment]
If you just enabled it and don't see the comments field, try refreshing the tab.

**Comment by rcmpayne** [comment]
i think i found the issue, you cant edit this info on google's music that you are paying for "streamed music" but rather only on music you have uploaded to google music.

**Comment by simon-weber** [comment]
Oh, interesting. Does that apply even if you add the store track to your library?

**Comment by rcmpayne** [comment]
ok so something is up here (bug i think) so i can right click on a track that i uploaded to google music and i can right click and edit the item. i can also right click and download the track. i check another track and i have the edit option but no download so i assume thats a song that i liked via the streaming service i pay for.

however, most of the others dont have either option.

**Comment by rcmpayne** [comment]
ok found the issue. I can edit the song in the Autoplay list Thumbs up that google created however, if i add that same song to a new playlist, i cant edit it.

**Comment by simon-weber** [comment]
Oh, bizarre. Nice work chasing it down.

Ok if I close this issue? I think everything is on Google now.

**Comment by simon-weber** [comment]
Feel free to reopen if there's still something to be done here.
