### ISSUE TITLE
expose explicitType

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/Autoplaylists-for-Google-Music#90]
Sourced from [this post](https://groups.google.com/d/msg/autoplaylists-for-google-music/ONRwcJZ8rX4/kKZripK4CQAJ).

**Comment by simon-weber** [comment]
@Yinka, do you have examples of the values this field takes? All I have in my library is null and 1.

**Comment by Yinka** [comment]
Does that mean 1 will be `explicit`? and null `not explicit` - sorry if that's not the answer you are expecting, I'm clueless about this :) 

Thanks for the new features too.

**Comment by simon-weber** [comment]
Ah, that's what I was hoping you could answer. I was wondering what you found in your library that made you want to use the field.

**Comment by simon-weber** [comment]
Turns out there are three values: yes/no/unknown.
