### ISSUE TITLE
Sync Time Setting Ignored

### ISSUE THREAD

**Issue by vbprog** [simon-weber/Autoplaylists-for-Google-Music#91]
Sync happens every time I open Google Music, regardless of the time period I use in settings. I currently have the setting set to 800. However everytime I open a new GM tab, my playlist resyncs. I would expect it to sync only once every ~13 hours.

**Comment by simon-weber** [comment]
Ah, good point.

Do you expect a sync to happen for only the first tab you open? Or for none of them (unless they sync interval has passed)? Both should be straightforward to implement, but I wonder if people have different expectations (implying it should be configurable).

**Comment by vbprog** [comment]
Hi Simon:

Yes I guess I expect it to only sync once during the interval specified, regardless of how many times I open GM. Here's my use case:

I set up an auto playlist for 250 random songs that have a playcount under 3. I have this playlist set to download on my phone so I can listen to these seldom played songs while travelling. _(I've been wanting this feature for as long as I've used GM)_ I might open GM several times throughout the day for various reasons - and the playlist wipes out on the phone and redownloads all 250 songs every time.

I guess I could set your sync setting to 0 and then change it once a day or whenever I want the playlist to do a resync....

I think in my mind if I set the sync time to 800 it shouldn't sync until that time has past.

**Comment by simon-weber** [comment]
Gotcha; totally makes sense. I actually have [a similar use case](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Tips-and-Tricks#pomodoro-playlist), though since I normally listen through the web, refreshing the playlist each time hasn't been a big deal.

I'll go with don't-sync-at-all-within-sync-period, and if folks complain then I'll add an option for refresh-always-syncs. I should have time for it this weekend. Thanks for bringing it up!

**Comment by simon-weber** [comment]
Here's how I'm planning for this to work on load:
* now >= last-sync + sync-period: sync immediately. Next sync at `now + sync-period`.
* now < last-sync + sync-period: don't sync. Next sync at `last-sync + sync-period`.

**Comment by simon-weber** [comment]
There's a very good chance there are bugs in this, so please play around with it once you get the update! I'm going to push it out now since I'm eager to fix an unrelated bug in the current release.
