### ISSUE TITLE
1k-track playlists may break syncing

### ISSUE THREAD

**Issue by yokaiichi** [simon-weber/Autoplaylists-for-Google-Music#98]
I've checked and double-checked and tested and double-tested an auto playlist that used to work fine but now isn't respecting a "Last Played" filter any more. The same is true for all my playlists.  The main thing I use this extension for is rotating in songs that I haven't played in 180-270 days. They all contain a clause "Last Played earlier than 270 days ago".

In the past, sure enough if I played 10 songs from the playlist (and it was already well below the "Limit" setting), I could see the playlist info reflecting that the playlist was 10 songs shorter than the last time I checked. You get the idea.

The playlists are no longer tossing out the songs I just played when synced. The total number never changes now. Which totally defeats the main thing I use this extension for.

**Comment by simon-weber** [comment]
I just tested this - the last played use case is an important one to me, too - and it seems to work for me. However, it doesn't look like the web client was automatically pulling in changes anymore. I had to refresh the Music tab to see the songs get rotated out. It's also possible Google is in the middle of rolling out a change and I haven't gotten it yet.

A few questions to narrow down what's going on:
* does a reload of the Music tab help? Or does the length still stay the same after that?
* are all of your playlists not updating? Or is it only the ones using the "last played" condition?
* when you test the playlist in the extension, does the length go down? Or does it stay the same, like the Music tab?
* after refreshing the tab, do you see the sync time in the playlist description change? Or is it always the same?
* are you playing the songs on the Music tab, or from a mobile client?
* do you see any errors or warnings in [your logs](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs)?

**Comment by yokaiichi** [comment]
1. F5 and Ctrl-F5 does not change the song count in the playlist, even though the "Synced" timestamp of the playlist does change as expected.
2. All my playlists rely on the Last Played condition.
3. Not only does the number in the test playlist stay the same, but the number in the test playlist is higher than the actual playlist. I was going to submit a different bug report that the new test playlist functionality seems broken too!  My actual playlist is stuck at 857 songs (max = 1000). The test playlist always comes in at 1381 entries.
4. Yes. Timestamp changes properly.
5. I'm playing the songs from the Google Play Music app on iOS 10. 
6. Several warnings and errors in the logs, listed below:

ERRORS:
https://play.google.com/music/services/loaduserplaylist?format=jsarray&u=0&…ASMEFNLVdiWGpBdlNWcXk5Qk5TVXE2aEU4Xy14X0V0Zm5mY1E6MTQ3NTM2Njc0NTkzOQ%3D%3D Failed to load resource: net::ERR_NETWORK_CHANGED
background.js:915failed to sync playlist [auto] -X Girl Objectconsole.(anonymous function) @ background.js:915
https://app.getsentry.com/api/66349/store/?sentry_version=7&sentry_client=raven-js%2F3.6.0&sentry_key=ea691c5833f34aa085df5e5aee9a46f3 Failed to load resource: net::ERR_NETWORK_CHANGED
https://play.google.com/music/services/addtrackstoplaylist?format=jsarray&u…ASMEFNLVdiWGpBdlNWcXk5Qk5TVXE2aEU4Xy14X0V0Zm5mY1E6MTQ3NTM2Njc0NTkzOQ%3D%3D Failed to load resource: net::ERR_NETWORK_CHANGED
background.js:915failed to sync playlist [auto] -X Alt/Dub/Trip/EW Objectabort: (e)always: ()complete: ()done: ()error: ()fail: ()getAllResponseHeaders: ()getResponseHeader: (e)overrideMimeType: (e)pipe: ()progress: ()promise: (e)readyState: 0responseText: ""setRequestHeader: (e,t)state: ()status: 0statusCode: (e)statusText: "error"success: ()then: ()__proto__: Objectconsole.(anonymous function) @ background.js:915
https://play.google.com/music/services/editplaylist?format=jsarray&u=0&xt=C…ASMEFNLVdiWGpBdlNWcXk5Qk5TVXE2aEU4Xy14X0V0Zm5mY1E6MTQ3NTM2Njc0NTkzOQ%3D%3D Failed to load resource: net::ERR_NETWORK_CHANGED
background.js:915request failed: https://play.google.com/music/services/editplaylist?format=jsarray&u=0&xt=C…ASMEFNLVdiWGpBdlNWcXk5Qk5TVXE2aEU4Xy14X0V0Zm5mY1E6MTQ3NTM2Njc0NTkzOQ%3D%3D Array[2] Objectconsole.(anonymous function) @ background.js:915
https://play.google.com/music/services/editplaylist?format=jsarray&u=0&xt=C…ASMEFNLVdiWGpBdlNWcXk5Qk5TVXE2aEU4Xy14X0V0Zm5mY1E6MTQ3NTM2Njc0NTkzOQ%3D%3D Failed to load resource: net::ERR_NETWORK_CHANGED
background.js:915request failed: https://play.google.com/music/services/editplaylist?format=jsarray&u=0&xt=C…ASMEFNLVdiWGpBdlNWcXk5Qk5TVXE2aEU4Xy14X0V0Zm5mY1E6MTQ3NTM2Njc0NTkzOQ%3D%3D Array[2] Objectconsole.(anonymous function) @ background.js:915
https://play.google.com/music/services/editplaylist?format=jsarray&u=0&xt=C…ASMEFNLVdiWGpBdlNWcXk5Qk5TVXE2aEU4Xy14X0V0Zm5mY1E6MTQ3NTM2Njc0NTkzOQ%3D%3D Failed to load resource: net::ERR_NETWORK_CHANGED
background.js:915request failed: https://play.google.com/music/services/editplaylist?format=jsarray&u=0&xt=C…ASMEFNLVdiWGpBdlNWcXk5Qk5TVXE2aEU4Xy14X0V0Zm5mY1E6MTQ3NTM2Njc0NTkzOQ%3D%3D Array[2] Objectconsole.(anonymous function) @ background.js:915
https://app.getsentry.com/api/66349/store/?sentry_version=7&sentry_client=raven-js%2F3.6.0&sentry_key=ea691c5833f34aa085df5e5aee9a46f3 Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)



WARNINGS:

background.js:915 giving up on syncPlaylistContents! Array[2]
background.js:915 giving up on syncPlaylistContents! Array[2]
background.js:915 giving up on syncPlaylistContents! Array[2]
background.js:915 skipping sync since playlist is being updated: [auto] -X Alt/Dub/Trip/EW
background.js:915 skipping sync since playlist is being updated: [auto] -X Thumbs Up
background.js:915 giving up on syncPlaylistContents! Array[2]
background.js:915 skipping sync since playlist is being updated: [auto] -X Girl
background.js:915 skipping sync since playlist is being updated: [auto] -X Rock/Goth
background.js:915 skipping sync since playlist is being updated: [auto] -X Alt/Dub/Trip/EW
background.js:915 skipping sync since playlist is being updated: [auto] -X Thumbs Up
background.js:915 giving up on syncPlaylistContents! Array[2]
background.js:915 giving up on syncPlaylistContents! Array[2]
background.js:915 giving up on syncPlaylistContents! Array[2]
background.js:915 skipping sync since playlist is being updated: [auto] -X Rock/Goth
background.js:915 giving up on syncPlaylistContents! Array[2]
background.js:915 giving up on syncPlaylistContents! Array[2]
background.js:915 giving up on syncPlaylistContents! Array[2]
background.js:915 giving up on syncPlaylistContents! Array[2]
background.js:915 giving up on syncPlaylistContents! Array[2]
background.js:915 giving up on syncPlaylistContents! Array[2]
background.js:915 giving up on syncPlaylistContents! Array[2]
background.js:915 giving up on syncPlaylistContents! Array[2]
background.js:915 giving up on syncPlaylistContents! Array[2]
9724console messages are not shown.
background.js:915 giving up on syncPlaylistContents! [Array[4], Array[2]]
background.js:915 giving up on syncPlaylistContents! [Array[4], Array[2]]
background.js:915 giving up on syncPlaylistContents! [Array[4], Array[2]]
background.js:915 giving up on syncPlaylistContents! [Array[4], Array[2]]
background.js:915 giving up on syncPlaylistContents! [Array[4], Array[2]]
background.js:915 giving up on syncPlaylistContents! [Array[4], Array[2]]

**Comment by yokaiichi** [comment]
Here's a copy of the log after disabling the extension again just now > Ctrl-F5 in the Play Music tab > re-enable the extension > Ctrl-F5 in the Play Music tab. File attached.

[blbompphddfibggfmmfcgjjoadebinem-1475408327995.zip](https://github.com/simon-weber/Autoplaylists-for-Google-Music/files/504915/blbompphddfibggfmmfcgjjoadebinem-1475408327995.zip)

**Comment by yokaiichi** [comment]
Here's another set of logs. This time I tested playing music directly from the browser tab. After fully playing through 4 songs, I refreshed (F5) the browser tab, then saved both the Errors log and the Warnings log.  Again, timestamp changes correctly but song count does not.

Here is the "info" description of the playlist conditions, in case that helps:

Synced 10/2/2016, 6:55:19 AM by Autoplaylists for Google Music™ to contain: ((genre contains (case ignored) "alternative" or genre contains (case ignored) "dubstep" or genre contains (case ignored) "triphop" or genre contains (case ignored) "west" or genre equals "downtempo") and (rating thumb equals "none" or rating thumb equals "up") and last played earlier than "270 days ago" and genre does not contain (case ignored) "mellow") sort by artist ascending.

[Downloads.zip](https://github.com/simon-weber/Autoplaylists-for-Google-Music/files/504918/Downloads.zip)

**Comment by yokaiichi** [comment]
Annnnnnndddddd.... Mystery solved. No bug. And I feel stupid, lol.

Looking at some of the messages in the log I tried changing criteria for the playlist to drop it below 1000 songs in the TEST function. Sure enough, playlist syncs fine after that. So it turns out that my >270 days condition was, over time, allowing the playlist size to creep past 1000+ songs, and that was borking everything.

Moral of the story, if a playlist containing a "Last Played" condition seems to stop working, go check the TEST function and see if you've suddenly crept past the 1000-song limit.

**Comment by simon-weber** [comment]
Nice work debugging this! Glad you got it working.

I'm surprised that 1k+ tracks would cause a problem: there's a limit both on the frontend (the one you see in the test interface) and [on the backend](https://github.com/simon-weber/Autoplaylists-for-Google-Music/blob/1c717968b30ea04230472df84aaf83c8ae9335c9/src/js/background.js#L139).

The "network changed" error seems like the root of the problem, but it's pretty odd: it usually means something is going on at an OS level. The only times I've seen it is when eg switching to a new wifi network. I don't _think_ that it's possible for Google to actually affect that level of the networking stack, unless we managed to trigger something catastrophic like a bug in the kernel, haha.

**Comment by yokaiichi** [comment]
Right. I assumed that if the playlist ever went over 1000 tracks, they would just be truncated to exactly 1000. And then after playing 10 songs, they would be removed from the list and during the next sync (which might still find over 1000 songs), it would simply truncate again at 1000, effectively adding 10 new songs to the playlist.

But that doesn't seem to be what's happening at all. Now it behaves like:

If sync returns more than 1000 songs,
Then throw error about result set being too large and abort.

**Comment by simon-weber** [comment]
Yup, that's how limited playlists are intended to work, and how they work when syncing is running normally. The 413 errors in this case are coming from sentry, my error reporting service, and should be benign (though I should probably stop sending such large traces to them). I'll track and fix that separately.

The ERR_NETWORK_CHANGED is definitely key to the issue, though it's hard to tell whether it's the root cause or just a symptom. Some digging shows Chrome can throw this in a variety of weird circumstances, like driver problems and misconfigured vpns: http://superuser.com/questions/747735/regularly-getting-err-network-changed-errors-in-chrome. Since I haven't heard of the extension triggering this for anyone else, my current bet is that there's something specific to your install that's causing it, which then causes the syncing problems.

Are you able to recreate the problem by upping the playlist's limit again? If you are, it'd be awesome if you could get get a full dump of the logs by clearing them, triggering the problem, enabling all the log levels, and then right-clicking and hitting "save as".

**Comment by confidentjohn** [comment]
Hi

I also have a very similar issue.
I have a playlist to show all tracks that have a playcount of less than 1
In the test this returns 3,530 Tracks of a total of 4000 (I've just joined Google Music)

<img width="855" alt="screen shot 2016-11-15 at 23 30 42" src="https://cloud.githubusercontent.com/assets/5180576/20328622/9f42073e-ab8b-11e6-8f35-0204afaa24c8.png">

However when this syncs to Google Music only 60 pull through,

in the logs i see.
playlist b9f982b7-6e93-4ec8-b1f5-531bd6af9fad has 60 entries. first 3
(followed by all the data)
then i also see
adding 540 tracks. first 5 are listed

followed by the warning
background.js:915 giving up on syncPlaylistContents!

i have attached the log file
[autosyncLog.txt](https://github.com/simon-weber/Autoplaylists-for-Google-Music/files/593386/autosyncLog.txt)

Cheers John

**Comment by confidentjohn** [comment]
Interestingly today I reenabled the extension. Still had the same issue. So I deleted the playlist and recreated it with exactly the same rules. This new version has created properly with all tracks. 

It feels like after a couple of syncs the playlist creation/ edit part is falling over

**Comment by simon-weber** [comment]
Yeah. My bet is it's the same problem as https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/104, just manifesting as a degradation rather than a full outage. This is good evidence that there's nothing obviously wrong with the requests we're making, or recreating the playlist would have had the same problem.

What's your sync interval set to? Setting it to something like 720 seems to fix a lot of these issues.

**Comment by simon-weber** [comment]
Feel free to open a new issue if this is still a problem.
